<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Delete' => 'Удалить',
    'Do you really want to delete selected elements?' => 'Вы уверены, что хотите удалить выбранные элементы?',
    '*unknown*' => '*неизвестно*',
    '--choose--' => '--выберите--',
    '--no--' => '--нет--',
    '0.5' => '0.5',
    'Id' => 'Id',
    'http://yupe.ru' => 'http://yupe.ru',
    'team@yupe.ru' => 'team@yupe.ru',
    'yupe team' => 'yupe team',
    'Alias' => 'Алиас',
    'This section describes category management' => 'В данном разделе представлены средства управления категориями',
    'You are adding translate in to {lang}!' => 'Вы добавляете перевод на {lang} язык!',
    'Do you really want to remove category?' => 'Вы уверены, что хотите удалить категорию?',
    'Directory "{dir}" is available for write! {link}' => 'Директория "{dir}" не доступна для записи! {link}',
    'Create category' => 'Добавить категорию',
    'Create category and close' => 'Добавить категорию и закрыть',
    'Create category and continue' => 'Добавить категорию и продолжить',
    'Add translate in to {lang}' => 'Добавить перевод на {lang} язык',
    'Create' => 'Добавление',
    'Record was created!' => 'Запись добавлена!',
    'Bad characters in {attribute} field' => 'Запрещенные символы в поле {attribute}',
    'Page was not found!' => 'Запрошенная страница не найдена!',
    'Change settings' => 'Изменить настройки',
    'Image' => 'Изображение',
    'Find category' => 'Искать категорию',
    'File uploading catalog (relatively Yii::app()->getModule("yupe")->uploadPath)' => 'Каталог для загрузки файлов (относительно Yii::app()->getModule("yupe")->uploadPath)',
    'Categories' => 'Категории',
    'Categories - show' => 'Категории - просмотр',
    'Categories - edit' => 'Категории - редактирование',
    'Categories - manage' => 'Категории - управление',
    'Categories/Sections' => 'Категории/разделы',
    'Category' => 'Категория',
    'Categories - create' => 'Категория - добавление',
    'Category was changed!' => 'Категория изменена!',
    'Short description' => 'Короткое описание',
    'Module for categories/sections management' => 'Модуль для управления категориями/разделами сайта',
    'On moderation' => 'На модерации',
    'Title' => 'Название',
    'Bad request. Please don\'t use similar requests anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
    'Description' => 'Описание',
    'Published' => 'Опубликовано',
    'Find category' => 'Поиск категорий',
    'Fields with' => 'Поля, отмеченные',
    'Menu items order' => 'Порядок следования в меню',
    'Show category' => 'Просмотр категории',
    'View category' => 'Просмотреть категорию',
    'Change' => 'Редактирование',
    'Change category' => 'Редактирование категории',
    'Change translation in to {lang}' => 'Редактировать перевод на {lang} язык',
    'Parent' => 'Родитель',
    'Save category and close' => 'Сохранить категорию и закрыть',
    'Save category and continue' => 'Сохранить категорию и продолжить',
    'Categories list' => 'Список категорий',
    'Status' => 'Статус',
    'Structure' => 'Структура',
    'Remove category' => 'Удалить категорию',
    'Manage' => 'Управление',
    'Category manage' => 'Управление категориями',
    'Targeting category was not found!' => 'Целевая категория не найдена!',
    'Draft' => 'Черновик',
    'Language' => 'Язык',
    'Language was not found!' => 'Язык не найден!',
    'create' => 'добавление',
    'are required' => 'обязательны.',
    'manage' => 'управление',
    'Select {field}' => 'Выберите {field}',
    'Manage categories' => 'Управление категориями',
    'Creating category' => 'Создание категории',
    'Removing category' => 'Удаление категории',
    'List of categories' => 'Просмотр списка категорий',
    'Editing categories' => 'Редактирование категорий',
    'Viewing categories' => 'Просмотр категорий',
);
