<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Congratulations!' => 'Συγχαρητήρια!',
  'Install Rights' => 'Εγκατάσταση Δικαιωμάτων',
  'Installation failed.' => 'Η εγκατάσταση απέτυχε.',
  'No' => 'Όχι',
  'Notice: All your existing data will be lost.' => 'Παρατήρηση:Όλα τα υπάρχοντα δεδομένα σας θα χαθούν.',
  'Please confirm if you wish to reinstall.' => 'Παρακαλούμε επιβεβαιώστε ότι επιθυμείτε να επαναλάβετε την εγκατάσταση.',
  'Rights has been installed succesfully.' => 'Τα Δικαιώματα εγκαταστάθηκαν με επιτυχία.',
  'Rights is already installed!' => 'Τα Δικαιώματα είναι ήδη εγκατεστημένα.',
  'Yes' => 'Ναι',
  'You can start by generating your authorization items' => 'Αρχίστε δημιουργώντας τα αντικείμενα εξουσιοδότησης.',
  'You must be logged in to install Rights.' => 'Πρέπει να είστε συνεδεμένος στην ιστοσελίδα  για να εγκαταστήσετε τα Δικαιώματα.',
  'here' => 'εδώ',
);
