<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '0.5'                                                         => '',
    'Email'                                                       => '',
    'Email for notifications'                                     => '',
    'ID'                                                          => '',
    'IP address'                                                  => '',
    'http://yupe.ru'                                              => '',
    'team@yupe.ru'                                                => '',
    'yupe team'                                                   => '',
    '{className}: Sending information about new site comment.'    => '',
    'Automatic comment confirmation'                              => '',
    'This section describes comment management'                   => '',
    'Do you really want to delete selected elements?'             => '',
    'Do you really want do remove comment?'                       => '',
    'Created at'                                                  => '',
    'Create comment'                                              => '',
    'Create comment and close'                                    => '',
    'Create comment and continue'                                 => '',
    'New post was created on site "{app}"!'                       => '',
    'Create'                                                      => '',
    'Record was not added! Fill form correct!'                    => '',
    'Requested page was not found!'                               => '',
    'Name'                                                        => '',
    'Find comments'                                               => '',
    'Verification code'                                           => '',
    'RSS records count'                                           => '',
    'Comments'                                                    => '',
    'Comments'                                                    => '',
    'Comments - show'                                             => '',
    'Comments - edit'                                             => '',
    'Comments - management'                                       => '',
    'Comment'                                                     => '',
    'Comment - create'                                            => '',
    'Comment was created!'                                        => '',
    'Comment was updated!'                                        => '',
    'Content'                                                     => '',
    'Maximum captcha length'                                      => '',
    'Minimum captcha length'                                      => '',
    'Model'                                                       => '',
    'Comments moderation'                                         => '',
    'Module for simple comments support'                          => '',
    'Comment was created on your site:
  Author: {author}
  Model/ID: {model}/{model_id}
  Comment text:  {comment}'                                   => '',
    'Captcha settings'                                            => '',
    'Bad request. Please don\'t repeate similar requests anymore' => '',
    'Module general settings'                                     => '',
    'Please, set "model" and "modelId" for "{widget}" widget!'    => '',
    'Find comments'                                               => '',
    'Show captcha for guests'                                     => '',
    'Fields with'                                                 => '',
    'Menu items order'                                            => '',
    'Accepted'                                                    => '',
    'Check'                                                       => '',
    'Show comment'                                                => '',
    'View comment'                                                => '',
    'Accepted tags'                                               => '',
    'Edit'                                                        => '',
    'Edit comment'                                                => '',
    'Parent'                                                      => '',
    'Site'                                                        => '',
    'Save comment and close'                                      => '',
    'Save comment and continue'                                   => '',
    'Spam'                                                        => '',
    'You comments is in validation. Thanks.'                      => '',
    'You record was created. Thanks.'                             => '',
    'Comments list'                                               => '',
    'Status'                                                      => '',
    'Default comments status'                                     => '',
    'Unknown status'                                              => '',
    'Text'                                                        => '',
    'Model type'                                                  => '',
    'You have {{count}} new comments. {{link}}'                   => '',
    'Notify about comment?'                                       => '',
    'Deleted'                                                     => '',
    'Delete'                                                      => '',
    'Delete comment'                                              => '',
    'Manage'                                                      => '',
    'Manage comments'                                             => '',
    'create'                                                      => '',
    'are require.'                                                => '',
    'manage'                                                      => '',
    'Antispam interval'                                           => '',
    'Spam protection, try to create comment after {few} minutes!' => '',
    'Last comments'                                               => '',
    'Reply'                                                       => '',
    'no comments, be first!'                                      => '',
    'There is an error when create comments, try again later.'    => '',
    'WRITE COMMENT'                                               => '',
    'From user'                                                   => '',
    'Insert symbols you see on picture'                           => '',
    'Creating comment'                                            => '',
    'Removing comment'                                            => '',
    'List of comments'                                            => '',
    'Editing comment'                                             => '',
    'Viewing comments'                                            => '',
    'Batch delete'                                                => '',
    'Remove tags in the derivation comment using strip_tags() ?'  => '',
    'Not have permission to add a comment!'                       => ''
];
