<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '0.1' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Авторизационные данные' => '',
  'Аккаунт привязан!' => '',
  'Вконтакте. ID приложения' => '',
  'Вконтакте. Защищенный ключ' => '',
  'Вы успешно авторизовались!' => '',
  'Запрошенная страница не найдена!' => '',
  'Модуль предназначен для интеграции Вашего сайта и социальных сетей =)' => '',
  'Модуль содержит компоненты и виджеты для взаимодействия с социальными сетями' => '',
  'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!' => '',
  'Пожалуйста, завершите регистрацию, имя пользователя "{nick_name}" к сожалению, уже занято...' => '',
  'Поиск' => '',
  'Поля, отмеченные * обязательны для заполнения' => '',
  'При авторизации произошла ошибка!' => '',
  'При авторизации через {servive} произошла ошибка!' => '',
  'При создании учетной записи произошла ошибка {error}!' => '',
  'При создании учетной записи произошла ошибка!' => '',
  'Просмотр' => '',
  'Просмотреть' => '',
  'Редактирование' => '',
  'Редактировать' => '',
  'Сервисы' => '',
  'Социализация' => 'Socialization',
  'Удалить' => '',
  'Управление' => '',
  'Учетная запись создана, но не удалось авторизоваться!' => '',
);
