<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '--choose--'                                                           => '',
    '--unknown--'                                                          => '',
    '0.1'                                                                  => '',
    'ID'                                                                   => '',
    'MainEvent with "{code}" code was not found!'                          => '',
    'MainEvent with code "{code}" don\'t contain any of active templates!' => '',
    'http://yupe.ru'                                                       => '',
    'team@yupe.ru'                                                         => '',
    'yupe team'                                                            => '',
    'This section contain mail messages management'                        => '',
    'This section contain mail message templates management'               => '',
    'Do you really want to remove?'                                        => '',
    'Create template'                                                      => '',
    'Create mail template'                                                 => '',
    'Create event'                                                         => '',
    'Create event and close'                                               => '',
    'Create event and continue'                                            => '',
    'Create template'                                                      => '',
    'Create template and close'                                            => '',
    'Create'                                                               => '',
    'Event creation'                                                       => '',
    'Template creation'                                                    => '',
    'Record was created!'                                                  => '',
    'Record was updated!'                                                  => '',
    'Record was removed!'                                                  => '',
    'Requested page was not found'                                         => '',
    'Requested page was not found.'                                        => '',
    'Find'                                                                 => '',
    'Component YMailMessage.mailComponent is not working!'                 => '',
    'For'                                                                  => '',
    'Module for mail message management'                                   => '',
    'Title'                                                                => '',
    'Bad request. Please don\'t repeate similar request anymore'           => '',
    'Description'                                                          => '',
    'From'                                                                 => '',
    'Error when sending mail!'                                             => '',
    'Find mail messages'                                                   => '',
    'Find mail templates'                                                  => '',
    'Fields, with'                                                         => '',
    'Mail events'                                                          => '',
    'Mail messages'                                                        => '',
    'Mail templates'                                                       => '',
    'View mail event'                                                      => '',
    'View mail template'                                                   => '',
    'Show template'                                                        => '',
    'View template'                                                        => '',
    'Edit'                                                                 => '',
    'Edit mail event'                                                      => '',
    'Edit mail message'                                                    => '',
    'Edit mail template'                                                   => '',
    'Edit event'                                                           => '',
    'Edit template'                                                        => '',
    'Edit template '                                                       => '',
    'Services'                                                             => '',
    'Symbolic code'                                                        => '',
    'Event'                                                                => '',
    'Create template and continue'                                         => '',
    'Message'                                                              => '',
    'Save event and close'                                                 => '',
    'Save event and continue'                                              => '',
    'Save template and close'                                              => '',
    'Save template and continue'                                           => '',
    'List'                                                                 => '',
    'Events list'                                                          => '',
    'Mail templates list'                                                  => '',
    'Messages list'                                                        => '',
    'Templates list'                                                       => '',
    'Status'                                                               => '',
    'Topic'                                                                => '',
    'Remove event'                                                         => '',
    'Remove template'                                                      => '',
    'Management'                                                           => '',
    'Template with "{code}" was not found!'                                => '',
    'Templates'                                                            => '',
    'active'                                                               => '',
    'adding'                                                               => '',
    'not active'                                                           => '',
    'are required.'                                                        => '',
    'management'                                                           => '',
    'Visual editor'                                                        => '',
    'Menu items order'                                                     => '',
    'Template'                                                             => '',
    'Select {field}'                                                       => '',
];
