<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  '--выберите--' => '',
  'ID' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Алиас' => '',
  'Артикул' => '',
  'В данном разделе представлены средства управления' => '',
  'Вы уверены, что хотите удалить товар?' => '',
  'Да' => '',
  'Данные' => '',
  'Директория "{dir}" не доступна для записи! {link}' => '',
  'Добавил' => '',
  'Добавить товар' => '',
  'Добавление' => '',
  'Добавлено' => '',
  'Доступен' => '',
  'Запись добавлена!' => '',
  'Запись обновлена!' => '',
  'Запись удалена!' => '',
  'Изменено' => '',
  'Изменил' => '',
  'Изменить настройки' => '',
  'Изображение' => '',
  'Искать товар' => '',
  'Каталог товаров' => '',
  'Категория' => '',
  'Контент' => '',
  'Короткое описание' => '',
  'Модуль для создания простого каталога товаров' => '',
  'Название' => '',
  'Не доступен' => '',
  'Нет' => '',
  'Нет в наличии' => '',
  'Описание' => '',
  'Поиск товаров' => '',
  'Поля, отмеченные' => '',
  'Просмотр товара' => '',
  'Просмотреть товар' => '',
  'Редактирование' => '',
  'Редактирование товара' => '',
  'Сохранить товар и закрыть' => '',
  'Сохранить товар и продолжить' => '',
  'Спецпредложение' => '',
  'Список товаров' => '',
  'Статус' => '',
  'Товар' => '',
  'Товар не найден!' => '',
  'Товары' => '',
  'Товары - добавление' => '',
  'Товары - просмотр' => '',
  'Товары - редактирование' => '',
  'Товары - управление' => '',
  'Удалить товар' => '',
  'Управление' => '',
  'Управление товарами' => '',
  'Цена' => '',
  'добавление' => '',
  'обязательны.' => '',
  'товарами' => '',
  'управление' => '',
);
