<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  '--нет--' => '',
  'Id' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Алиас' => '',
  'Добавить категорию' => '',
  'Добавление категории' => '',
  'Изменение категории' => '',
  'Изменить категорию' => '',
  'Категории' => '',
  'Категории/разделы' => '',
  'Модуль для управления категориями/разделами сайта' => '',
  'На модерации' => '',
  'Название' => '',
  'Неверный формат поля "{attribute}" допустимы только буквы, цифры и символ подчеркивания, от 2 до 20 символов' => '',
  'Описание' => '',
  'Опубликовано' => '',
  'Поиск' => '',
  'Поиск категорий' => '',
  'Порядок следования в меню' => '',
  'Просмотр категории' => '',
  'Просмотреть категорию' => '',
  'Родитель' => '',
  'Сохранить измнения' => '',
  'Список категорий' => '',
  'Статус' => '',
  'Структура' => '',
  'Удалить категорию' => '',
  'Управление' => '',
  'Управление категориями' => '',
  'Черновик' => '',
);
