<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '0.1 (dev)' => '',
  '0.3' => '',
  'Email' => '',
  'Email для уведомлений?' => '',
  'http://yupe.ru' => '',
  'id' => '',
  'ip' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Автоматическое подтверждение комментариев' => '',
  'Вы действительно хотите удалить выбранный комментарий?' => '',
  'Дата создания' => '',
  'Добавить комментарий' => '',
  'Добавлен новый комментарий на сайте "{app}"!' => '',
  'Добавление' => '',
  'Добавление комментария' => '',
  'Имя' => '',
  'Код проверки' => '',
  'Комментарии' => '',
  'Комментарий' => '',
  'Комментарий добавлен!' => '',
  'Комментарий не добавлен!' => '',
  'Комментарий не добавлен! Заполните форму корректно!' => '',
  'Контент' => '',
  'Модель' => '',
  'Модуль для простых комментариев' => '',
  'От имени' => '',
  'Пожалуйста, укажите "model" и "modelId" для виджета "{widget}" !' => '',
  'Поиск' => '',
  'Поиск комментариев' => '',
  'Порядок следования в меню' => '',
  'Принят' => '',
  'Проверка' => '',
  'Просмотр комментария' => '',
  'Просмотреть комментарий' => '',
  'Редактирование' => '',
  'Редактирование комментария' => '',
  'Редактировать комментарий' => '',
  'Сайт' => '',
  'Сохранить комментарий' => '',
  'Спам' => '',
  'Спасибо, Ваш комментарий добавлен и ожидает проверки!' => '',
  'Спасибо, Ваш комментарий добавлен!' => '',
  'Список комментариев' => '',
  'Статус' => '',
  'Статус комментариев по умолчанию' => '',
  'Статус неизвестен' => '',
  'Страница не найдена!' => '',
  'Тип модели' => '',
  'У Вас {{count}} новых комментариев' => '',
  'Уведомить о новом комментарии?' => '',
  'Удален' => '',
  'Удалить комментарий' => '',
  'Управление' => '',
  'Управление комментариями' => '',
);
