<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '0.1 (dev)' => '',
  '0.4' => '',
  'Email' => '',
  'Email для уведомлений?' => '',
  'http://yupe.ru' => '',
  'id' => '',
  'ip' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Автоматическое подтверждение комментариев' => '',
  'Дата создания' => '',
  'Добавлена новая запись на сайте "{app}"!' => '',
  'Запись не добавлена!' => '',
  'Запись не добавлена! Заполните форму корректно!' => '',
  'Имя' => '',
  'Код проверки' => '',
  'Комментариев' => '',
  'Комментарии' => '',
  'Комментарий добавлен!' => '',
  'Контент' => '',
  'Модель' => '',
  'Модерация комментариев' => '',
  'Модуль для простых комментариев' => '',
  'Пожалуйста, укажите "model" и "modelId" для виджета "{widget}" !' => '',
  'Порядок следования в меню' => '',
  'Принят' => '',
  'Проверка' => '',
  'Сайт' => '',
  'Спам' => '',
  'Спасибо, Ваша запись добавлена и ожидает проверки!' => '',
  'Спасибо, Ваша запись добавлена!' => '',
  'Статус' => '',
  'Статус комментариев по умолчанию' => '',
  'Статус неизвестен' => '',
  'Страница не найдена!' => '',
  'Текст' => '',
  'Тип модели' => '',
  'У Вас {{count}} новых комментариев. {{link}}' => '',
  'Уведомить о новом комментарии?' => '',
  'Удален' => '',
);
