<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестный тип*' => '',
  '0.2' => '',
  'HTML код' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Блоки контента' => '',
  'Добавить блок' => '',
  'Исполняемый PHP код' => '',
  'Контент' => '',
  'Контент блок "{code}" не найден !' => '',
  'Модуль для создания и редактирования произвольных блоков контента' => '',
  'Название' => '',
  'Неверный формат поля "{attribute}" допустимы только буквы, цифры и символ подчеркивания, от 2 до 50 символов' => '',
  'Описание' => '',
  'Простой текст' => '',
  'Символьный код' => '',
  'Список блоков' => '',
  'Тип' => '',
  'Укажите название контент блока для ContentBlockWidget!' => '',
);
