<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  'id' => '',
  'yupe team' => '',
  'Автор' => '',
  'Для участия в конкурсе Вам необходимо ' => '',
  'Добавить изображение' => '',
  'Добавить конкурс' => '',
  'Добавление' => '',
  'Добавление изображения в конкурс' => '',
  'Добавление конкурса' => '',
  'Добавление фото' => '',
  'Завершение' => '',
  'Завершение голосования' => '',
  'Изменить конкурс' => '',
  'Изображения в этом конкурсе' => '',
  'Количество фото' => '',
  'Конкурс' => '',
  'Конкурсы изображений' => '',
  'Модуль для простых конкурсов изображений' => '',
  'Название' => '',
  'Начало' => '',
  'Начало голосования' => '',
  'Описание' => '',
  'Опубликовано' => '',
  'Поиск' => '',
  'Порядок следования в меню' => '',
  'При добавлении изображения произошла ошибка!' => '',
  'Произошла ошибка!' => '',
  'Просмотр' => '',
  'Просмотр конкурса' => '',
  'Редактирование' => '',
  'Редактирование конкурса' => '',
  'Сервисы' => '',
  'Сохранить изменения' => '',
  'Список' => '',
  'Список конкурсов' => '',
  'Статус' => '',
  'Страница не найдена!' => '',
  'Удалить конкурс' => '',
  'Управление' => '',
  'Управление конкурсами' => '',
  'Фотография добавлена!' => '',
  'Черновик' => '',
);
