<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    '*неизвестный тип*' => '',
    '0.2' => '',
    'HTML код' => '',
    'aopeykin@yandex.ru' => '',
    'http://yupe.ru' => '',
    'xoma' => '',
    'Блоки контента' => '',
    'Добавить блок' => '',
    'Добавить блок контента' => '',
    'Добавить новый блок' => '',
    'Добавление блока контента' => '',
    'Добавление нового блока' => '',
    'Искать' => '',
    'Исполняемый PHP код' => '',
    'Код для использования этого блока в шаблоне:' => '',
    'Контент' => '',
    'Контент блок "{code}" не найден !' => '',
    'Модуль для создания и редактирования произвольных блоков контента' => '',
    'Название' => '',
    'Описание' => '',
    'Поиск' => '',
    'Поля, отмеченные * обязательны для заполнения' => '',
    'Просмотр блока контента' => '',
    'Просмотреть этот блок контента' => '',
    'Простой текст' => '',
    'Редактирование блока контента' => '',
    'Редактировать этот блок контента' => '',
    'Символьный код' => '',
    'Сохранить изменения' => '',
    'Список блоков' => '',
    'Список блоков контента' => '',
    'Тип' => '',
    'Удалить этот блок контента' => '',
    'Удалить этот элемент ?' => '',
    'Укажите название контент блока для ContentBlockWidget !' => '',
    'Управление' => '',
    'Управление блоками контента' => '',
);
