<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    '0.2' => '',
    'Email' => '',
    'Email от имени которого отправлять сообщение' => '',
    'Ip-адрес' => '',
    'aopeykin@yandex.ru' => '',
    'http://yupe.ru' => '',
    'В разделе FAQ' => '',
    'Ваше сообщение отправлено! Спасибо!' => '',
    'Да' => '',
    'Дата изменения' => '',
    'Дата ответа' => '',
    'Дата создания' => '',
    'Добавить в faq' => '',
    'Добавить сообщение' => '',
    'Добавление сообщения' => '',
    'Идентификатор' => '',
    'Изменить' => '',
    'Изменить данное сообщение' => '',
    'Имя' => '',
    'Модуль для работы с сообщениями с сайта' => '',
    'Неизвестный тип сообщения!' => '',
    'Нет' => '',
    'Новое сообщение' => '',
    'Обратная связь' => '',
    'Обращение пользователя добавлено в базу!' => '',
    'Обращение пользователя отправлено на email!' => '',
    'xoma' => '',
    'Ответ' => '',
    'Ответ отправлен' => '',
    'Ответил' => '',
    'Ответить на сообщение' => '',
    'Отправить ответ' => '',
    'Ошибка при добавлении обращения пользователя в базу!' => '',
    'Поиск' => '',
    'Поиск сообщений' => '',
    'Показывать капчу' => '',
    'Порядок следования в меню' => '',
    'При отправке сообщения произошла ошибка! Повторите попытку позже!' => '',
    'Просмотр сообщения с сайта' => '',
    'Просмотреть данное сообщение' => '',
    'Редактировать сообщение с сайта ' => '',
    'Сообщение в обработке' => '',
    'Сообщение обработано' => '',
    'Сообщения с сайта' => '',
    'Сохранить изменения' => '',
    'Список сообщений' => '',
    'Статус' => '',
    'Статус сообщения неизвестен' => '',
    'Текст' => '',
    'Тема' => '',
    'Тип' => '',
    'Удалить данное сообщение' => '',
    'Укажите email для обратной связи! application.modules.feedback.FeedBackModule.emails' => '',
    'Укажите корректное значение для свойтсва application.modules.feedback.FeedBackModule.backEnd - "db" и/или "email"!' => '',
    'Управление' => '',
    'Управление сообщениями' => '',
);
