<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  'Id' => '',
  'http://yupe.ru' => '',
  'id' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'В данном разделе представлены средства управления' => '',
  'Вы уверены, что хотите удалить галерею?' => '',
  'Галереи' => '',
  'Галереи - добавление' => '',
  'Галереи - просмотр' => '',
  'Галереи - редактирование' => '',
  'Галереи - управление' => '',
  'Галереи изображений' => '',
  'Галерея' => '',
  'Дата добавления' => '',
  'Добавить галерею' => '',
  'Добавление' => '',
  'Запись добавлена!' => '',
  'Запись обновлена!' => '',
  'Запись удалена!' => '',
  'Изображение' => '',
  'Искать галерею' => '',
  'Модуль для простых галерей изображений' => '',
  'Название' => '',
  'Описание' => '',
  'Поиск галерей' => '',
  'Поля, отмеченные' => '',
  'Порядок следования в меню' => '',
  'При добавлении изображения произошла ошибка!' => '',
  'Просмотр галереи' => '',
  'Просмотреть галерею' => '',
  'Редактирование' => '',
  'Редактирование галереи' => '',
  'Сервисы' => '',
  'Список галерей' => '',
  'Статус' => '',
  'Страница не найдена!' => '',
  'Удалить галерею' => '',
  'Управление' => '',
  'Управление галереями' => '',
  'Фотография добавлена!' => '',
  'галереи' => '',
  'галереями' => '',
  'добавление' => '',
  'обязательны.' => '',
  'опубликовано' => '',
  'скрыто' => '',
  'управление' => '',
);
