<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  'Id' => '',
  'http://yupe.ru' => '',
  'id' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Автор' => '',
  'Вы уверены, что хотите удалить галерею ?' => '',
  'Галереи изображений' => '',
  'Галерея' => '',
  'Дата добавления' => '',
  'Для добавления фото Вам необходимо ' => '',
  'Добавить галерею' => '',
  'Добавить изображение' => '',
  'Добавление галереи' => '',
  'Добавление изображения в галерею' => '',
  'Добавление фото' => '',
  'Изменить галерею' => '',
  'Изображение' => '',
  'Кокурсы' => '',
  'Количесво фото' => '',
  'Количество фото' => '',
  'Модуль для простых галерей изображений' => '',
  'Название' => '',
  'Описание' => '',
  'Поиск' => '',
  'Порядок следования в меню' => '',
  'При добавлении изображения произошла ошибка!' => '',
  'Просмотр галереи' => '',
  'Просмотреть галерею' => '',
  'Редактирование галереи' => '',
  'Сервисы' => '',
  'Сохранить галерею' => '',
  'Список галерей' => '',
  'Статус' => '',
  'Страница не найдена!' => '',
  'Удалить галерею' => '',
  'Управление галереями' => '',
  'Фотографии в этой галереи' => '',
  'Фотография добавлена!' => '',
  'авторизоваться' => '',
  'опубликовано' => '',
  'скрыто' => '',
);
