<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  'http://yupe.ru' => '',
  'id' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Альтернативный текст' => '',
  'Главная категория изображений' => '',
  'Дата создания' => '',
  'Директория "{dir}" не доступна для записи или не существует! {link}' => '',
  'Добавил' => '',
  'Добавить изображение' => '',
  'Изменить настройки модуля' => '',
  'Изображение добавлено!' => '',
  'Изображения' => '',
  'Картинка' => '',
  'Каталог для загрузки изображений' => '',
  'Категория' => '',
  'Контент' => '',
  'Максимальный размер (в байтах)' => '',
  'Модуль для хранения изображений' => '',
  'Название' => '',
  'Описание' => '',
  'Пожалуйста, укажите каталог для хранения изображений! {link}' => '',
  'Превью' => '',
  'При удалении файла произошла ошибка!' => '',
  'Разрешенные расширения (перечислите через запятую)' => '',
  'Родитель' => '',
  'Статус' => '',
  'Тип картинки' => '',
  'Укажите максимальный размер изображений {link}' => '',
  'Файл' => '',
  'доступно' => '',
  'требуется проверка' => '',
);
