<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '0.2' => '',
  'Email' => '',
  'Email администратора' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Ваш сайт готов к работе!' => '',
  'Если Вам не жалко - отправьте нам чуть-чуть денежек, мы будем довольны =) !' => '',
  'Имя пользователя' => '',
  'Исходный код на Github' => '',
  'Ключевые слова сайта' => '',
  'Модуль для установки системы' => '',
  'Название базы данных' => '',
  'Название сайта' => '',
  'Необходима помощь?' => '',
  'Описание сайта' => '',
  'Официальный сайт Юпи!' => '',
  'Официальный твиттер Юпи!' => '',
  'ПЕРЕЙТИ В ПАНЕЛЬ УПРАВЛЕНИЯ' => '',
  'ПЕРЕЙТИ НА САЙТ' => '',
  'Пароли не совпадают!' => '',
  'Пароль' => '',
  'Пишите нам на <b>team@yupe.ru</b>' => '',
  'Подтверждение пароля' => '',
  'Поздравляем, установка Юпи! завершена!' => '',
  'Полезные ссылки:' => '',
  'Пользователь' => '',
  'Порт' => '',
  'Система' => '',
  'Сокет' => '',
  'Укажите параметры соединения с базой данных' => '',
  'Установка' => '',
  'Установщик' => '',
  'Форум поддержки Юпи!' => '',
  'Хост' => '',
  'заходите чаще =)' => '',
  'интересные мысли и идеи =)' => '',
  'используется для авторизации в панели управления)' => '',
  'обязательно заффоловьте нас, мы не спамим =)' => '',
  'принимаем всякого рода коммерческие и любые предложения =)' => '',
  'пришлите нам парочку пулл-реквестов, все только выиграют =)' => '',
);
