<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '0.2' => '',
  'Email' => '',
  'Host' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Если Вам не жалко - отправьте нам чуть-чуть денежек, мы будем довольны =) !' => '',
  'Задайте вопрос на форуме' => '',
  'заходите чаще =)' => '',
  'заходите, поболтаем =)' => '',
  'пришлите нам парочку пулл-реквестов, все только выиграют =)' => '',
  'Укажите параметры соединения с базой данных' => 'Please, specify your database connection settings',
  'Email администратора' => 'Administrator\'s EMail',
  'Ваш сайт готов к работе!' => 'Your site is ready!',
  'Имя пользователя' => 'User name',
  'Исходный код на Github' => 'Source code on Github',
  'Ключевые слова сайта' => 'Site keywords',
  'Модуль для установки системы' => 'Module for system installation',
  'Название базы данных' => 'DB name',
  'Название сайта' => 'Site name',
  'Напишите нам на <b>team@yupe.ru</b>' => 'Feel free to write for us on <b>team@yupe.ru</b>',
  'Описание сайта' => 'Site description',
  'Официальный сайт Юпи!' => 'Yupe! official site',
  'Официальный твиттер Юпи!' => 'Yupe! official twitter',
  'ПЕРЕЙТИ В ПАНЕЛЬ УПРАВЛЕНИЯ' => 'GO TO THE CONTROL PANEL',
  'Пароли не совпадают!' => 'Passwords mismatch',
  'Пароль' => 'Password',
  'Подтверждение пароля' => 'Confirm password',
  'Поздравляем, установка Юпи! завершена!' => 'Congratulations, Yupe! setup is done!',
  'Полезные ссылки:' => 'Useful links:',
  'Пользователь' => 'User',
  'Порт' => 'Port',
  'Установка' => 'Setup',
  'Установщик' => 'Installer',
  'Ядрышко' => 'Core',
  'используется для авторизации в панели управления)' => 'used for control panel authorization',
  'обязательно заффоловьте нас, мы не спамим =)' => 'please, follow us, we promise not to send spam =)',
  'принимаем всякого рода коммерческие и любые предложения =)' => 'we are accepting for any commercial or non-commercial offers',
);
