<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '--неизвестно--' => '',
  'ID' => '',
  'MailEvent c кодом "{code}" не найден!' => '',
  'MailEvent c кодом "{code}" не содержит ни одного активного шаблона!' => '',
  'YMailMessage.mailComponent is invalid!' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Запись добавлена!' => '',
  'Запись обновлена!' => '',
  'Запись удалена!' => '',
  'Кому' => '',
  'Модуль управления почтовыми сообщениями' => '',
  'Название' => '',
  'Описание' => '',
  'От' => '',
  'Ошибка отправка почты!' => '',
  'Почтовые сообщения' => '',
  'Символьный код' => '',
  'Система' => '',
  'Событие' => '',
  'Сообщение' => '',
  'Статус' => '',
  'Тема' => '',
  'Шаблон с кодом "{code}" не найден!' => '',
  'активен' => '',
  'не активен' => '',
);
