<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  '--выберите значение--' => '',
  '0.3 (dev)' => '',
  'Cписок пунктов меню' => '',
  'Id' => '',
  'Wiki' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Адрес' => '',
  'Добавить меню' => '',
  'Добавить пункт меню' => '',
  'Добавление' => '',
  'Добавление нового меню' => '',
  'Добавление нового пункта меню' => '',
  'Заголовок' => '',
  'Запрещенные символы в поле {attribute}' => '',
  'Изменить меню' => '',
  'Изменить пункт меню' => '',
  'Контент' => '',
  'Корень меню' => '',
  'Меню' => '',
  'Модуль для создания и редактирования меню' => '',
  'Модуль для создания раздела wiki' => '',
  'Название' => '',
  'Нет условия' => '',
  'Описание' => '',
  'Отрицание условия' => '',
  'Подтверждаете удаление?' => '',
  'Поиск' => '',
  'Почтовые шаблоны' => '',
  'Просмотр меню' => '',
  'Просмотр пункта меню' => '',
  'Пунктов' => '',
  'Пункты меню' => '',
  'Редактирование' => '',
  'Редактирование меню' => '',
  'Редактирование пункта меню' => '',
  'Родитель' => '',
  'Сортировка' => '',
  'Сохранить меню' => '',
  'Сохранить пункт меню' => '',
  'Список меню' => '',
  'Статус' => '',
  'Структура' => '',
  'Удалить меню' => '',
  'Удалить пункт меню' => '',
  'Уникальный код' => '',
  'Управление меню' => '',
  'Управление пунктами меню' => '',
  'Условие' => '',
  'активно' => '',
  'да' => '',
  'не активно' => '',
  'нет' => '',
  'отрицание' => '',
);
