<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    '*неизвестно*' => '',
    '0.1' => '',
    'Id' => '',
    'Url' => '',
    'aopeykin@yandex.ru' => '',
    'http://yupe.ru' => '',
    'Автор' => '',
    'Дата' => '',
    'Дата изменения' => '',
    'Дата создания' => '',
    'Добавить новость' => '',
    'Добавление новости' => '',
    'Доступ: * только для авторизованных пользователей' => '',
    'Заголовок' => '',
    'Запрещенные символы в поле {attribute}' => '',
    'Ключевые слова (SEO)' => '',
    'Контент' => '',
    'Короткое описание' => '',
    'Модуль для создания и редактирования новостей' => '',
    'На модерации' => '',
    'Новости' => '',
    'Новость не найдена!' => '',
    'xoma' => '',
    'Описание (SEO)' => '',
    'Опубликовано' => '',
    'Оставьте пустым для автоматической генерации' => '',
    'Поиск' => '',
    'Поиск новостей' => '',
    'Полный текст' => '',
    'Поля, отмеченные * обязательны для заполнения' => '',
    'Порядок следования в меню' => '',
    'Просмотр новости' => '',
    'Просмотреть новость' => '',
    'Редактирование новости' => '',
    'Редактировать новость' => '',
    'Сохранить изменения' => '',
    'Список новостей' => '',
    'Статус' => '',
    'Удалить новость' => '',
    'Управление' => '',
    'Управление новостями' => '',
    'Черновик' => '',
    'да' => '',
    'нет' => '',
);
