<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  'Id' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Автор' => '',
  'Алиас' => '',
  'Визуальный редактор' => '',
  'Главная категория новостей' => '',
  'Главная категория страниц' => '',
  'Дата' => '',
  'Дата изменения' => '',
  'Дата создания' => '',
  'Директория "{dir}" не доступна для записи! {link}' => '',
  'Добавить новость' => '',
  'Доступ: * только для авторизованных пользователей' => '',
  'Заголовок' => '',
  'Запрещенные символы в поле {attribute}' => '',
  'Изменить настройки' => '',
  'Изображение' => '',
  'Каталог для загрузки файлов (относительно Yii::app()->getModule("yupe")->uploadPath)' => '',
  'Категория' => '',
  'Ключевые слова (SEO)' => '',
  'Контент' => '',
  'Короткий текст' => '',
  'Модуль для создания и публикации новостей' => '',
  'На модерации' => '',
  'Новости' => '',
  'Новость не найдена!' => '',
  'Описание (SEO)' => '',
  'Опубликовано' => '',
  'Полный текст' => '',
  'Порядок следования в меню' => '',
  'Список изображений' => '',
  'Список новостей' => '',
  'Ссылка' => '',
  'Статус' => '',
  'Товар не найдена!' => '',
  'Черновик' => '',
  'Язык' => '',
  'да' => '',
  'нет' => '',
);
