<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '*неизвестно*' => '',
  'Email администратора' => '',
  'Id' => '',
  'Url' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'В меню' => '',
  'Визуальный редактор' => '',
  'Для просмотра этой страницы Вам необходимо авторизоваться!' => '',
  'Добавить страницу' => '',
  'Доступ: * только для авторизованных пользователей' => '',
  'Заголовок' => '',
  'Запрещенные символы в поле {attribute}' => '',
  'Изменено' => '',
  'Изменил' => '',
  'Категория' => '',
  'Ключевые слова (SEO)' => '',
  'Контент' => '',
  'Модуль для создания и редактирования страничек сайта' => '',
  'На модерации' => '',
  'Описание (SEO)' => '',
  'Опубликовано' => '',
  'Поля, отмеченные * обязательны для заполнения' => '',
  'Порядок следования в меню' => '',
  'Родитель' => '',
  'Создал' => '',
  'Создано' => '',
  'Сортировка' => '',
  'Список страниц' => '',
  'Статус' => '',
  'Страница не найдена!' => '',
  'Страницы' => '',
  'Текст' => '',
  'Черновик' => '',
  'Язык' => '',
  'да' => '',
  'нет' => '',
);
