<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Действия' => 'Actions',
  '*неизвестно*' => '*unknown*',
  '- не важно -' => '- any -',
  '- не выбрана -' => '- not selected -',
  '--нет--' => '--no--',
  '<span class=\'label label-success\'>Опубликовано</span> &ndash; Страницу видят все посетители сайта, режим по-умолчанию.<br /><br /><span class=\'label label-default\'>Черновик</span> &ndash; Данная страница еще не окончена и не должна отображаться.<br /><br /><span class=\'label label-info\'>На модерации</span> &ndash; Данная страница еще не проверена и не должна отображаться.' => '',
  'Id' => 'id',
  'Url' => 'Url',
  'http://yupe.ru' => 'http://yupe.ru',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
  'Блоги' => 'Blogs',
  'Визуальный редактор' => 'WYSIWYG Visual editor',
  'Дата изменения' => 'Update date',
  'Дата создания' => 'Creation date',
  'Для просмотра этой страницы Вам необходимо авторизоваться!' => 'To view this page you must login!',
  'Добавить и закрыть' => 'Save and Close',
  'Добавить страницу' => 'Create a page',
  'Добавить страницу и продолжить редактирование' => 'Create page and continue to edit',
  'Добавление новой страницы' => 'New page creation',
  'Добавление страницы' => 'Page creation',
  'Доступ: * только для авторизованных пользователей' => 'Access: * only for authenticated users',
  'Заголовок' => 'Title',
  'Записи' => 'Records',
  'Запрещенные символы в поле {attribute}' => 'Forbidden symbols in {attribute} field',
  'Изменение' => 'Updated',
  'Изменил' => 'Updated by',
  'Искать' => 'Search',
  'Ключевые слова (SEO)' => 'Keywords (SEO)',
  'Ключевые слова необходимы для SEO-оптимизации страниц сайта. Выделите несколько основных смысловых слов из страницы и напишите их здесь через запятую. К примеру, если страница содержит контактную информацию, логично использовать такие ключевые слова: <pre>адрес, карта проезда, контакты, реквизиты</pre>  ' => '',
  'Контент' => 'Content',
  'Краткое название страницы латинскими буквами, используется для формирования её адреса.<br /><br /> Например (выделено темным фоном): <pre>http://site.ru/page/<span class=\'label\'>contacts</span>/</pre> Если вы не знаете, для чего вам нужно это поле &ndash; не заполняйте его, заголовка страницы будет достаточно.' => '',
  'Краткое описание данной страницы, одно или два предложений. Обычно это самая главная мысль, к примеру: <pre>Контактная информация, реквизиты и карта проезда компании ОАО &laquo;Рога-унд-Копыта индастриз&raquo;</pre>Данный текст очень часто попадает в <a href=\'http://help.yandex.ru/webmaster/?id=1111310\'>сниппет</a> поисковых систем.' => '',
  'Модуль для создания и редактирования страничек сайта' => 'Module for static text pages creation and editing',
  'На модерации' => 'On review',
  'Название в меню' => 'Title in menu',
  'Описание (SEO)' => 'Description (SEO)',
  'Опубликовано' => 'Published',
  'Основное меню' => 'Main menu',
  'Оставьте пустым для автоматической генерации' => 'Keep empty for automatic generation',
  'Подтверждаете удаление страницы ?' => 'Proceed with page deletion?',
  'Поиск страниц' => 'Pages search',
  'Поля, отмеченные * обязательны для заполнения' => 'Fields, marked with * are required',
  'Порядок в меню' => 'Menu order',
  'Порядок следования в меню' => 'Menu order',
  'Посмотреть на сайте' => 'View on site',
  'Просмотр страницы' => 'Page view',
  'Просмотреть на сайте' => 'View this page on site',
  'Редактирование страницы' => 'Page edit',
  'Редактировать эту страницу' => 'Edit this page',
  'Родительская страница' => 'Parent page',
  'Создал' => 'Created by',
  'Создать' => 'Create',
  'Сохранить и закрыть' => 'Save and Close',
  'Сохранить и продолжить редактирование' => 'Save and continue to edit',
  'Список страниц' => 'Pages list',
  'Статус' => 'State',
  'Страница не найдена!' => 'Page not found!',
  'Страницы' => 'Pages',
  'Текст' => 'Text',
  'Удалить эту страницу' => 'Remove this page',
  'Укажите краткое название данной страницы для отображения её в меню.<br/><br />Например:<pre>Контакты</pre>' => '',
  'Укажите полное название данной страницы для отображения в заголовке при полном просмотре.<br/><br />Например:<pre>Контактная информация и карта проезда.</pre>' => '',
  'Управление' => 'Manage',
  'Управление страницами' => 'Pages management',
  'Чем большее числовое значение вы укажете в этом поле, тем выше будет позиция данной страницы в меню.' => '',
  'Черновик' => 'Draft',
  'Язык' => 'Language',
  'да' => 'yes',
  'добавление новой' => '',
  'нет' => 'no',
);
