<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Cannot create more than one root in single root mode.'                              => '',
    'Many roots mode is off.'                                                            => '',
    'The node already is root node.'                                                     => '',
    'The node cannot be deleted because it is already deleted.'                          => '',
    'The node cannot be deleted because it is new.'                                      => '',
    'The node cannot be inserted because it is deleted.'                                 => '',
    'The node cannot be inserted because it is not new.'                                 => '',
    'The node cannot be inserted because target node is deleted.'                        => '',
    'The node should not be deleted.'                                                    => '',
    'The node should not be new record.'                                                 => '',
    'The target node should not be deleted.'                                             => '',
    'The target node should not be descendant.'                                          => '',
    'The target node should not be root.'                                                => '',
    'The target node should not be self.'                                                => '',
    'You should not use CActiveRecord::delete() method when NestedSetBehavior attached.' => '',
    'You should not use CActiveRecord::save() method when NestedSetBehavior attached.'   => '',
];
