<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    '0.1' => '',
    'Layout административной части' => '',
    'Yii модули' => '',
    'Yii работает в режиме отладки, пожалуйста, отключите его! <br/> <a href="http://www.yiiframework.ru/doc/guide/ru/topics.performance">Подробнее про улучшение производительности Yii приложений</a>' => '',
    'aopeykin@yandex.ru' => '',
    'http://yupe.ru' => '',
    'id' => '',
    'Автор' => '',
    'Без этого модуля ничего не работает =)' => '',
    'Версия' => '',
    'Войти' => '',
    'Выберите тему' => '',
    'Выбор темы оформления' => '',
    'Выйти' => '',
    'Главная' => '',
    'Дальнейшая установка невозможна, пожалуйста, исправьте ошибки!' => '',
    'Директория "{dir}" не досутпна для записи!' => '',
    'Добро пожаловать в панель управления Вашим сайтом!' => '',
    'К сожалению для данного модуля нет доступных для редактирования параметров...' => '',
    'Ключевые слова сайта' => '',
    'Модули разработанные специально для ' => '',
    'Модуль не найден!' => '',
    'На сайт' => '',
    'Название' => '',
    'Название сайта' => '',
    'Настройки' => '',
    'Настройки модуля' => '',
    'Настройки модуля сохранены!' => '',
    'Настройки сохранены!' => '',
    'xoma' => '',
    'Описание' => '',
    'Описание сайта' => '',
    'Основные параметры' => '',
    'Оформление' => '',
    'Панель управления' => '',
    'Порядок следования в меню' => '',
    'При сохранении произошла ошибка!' => '',
    'Сохранить настройки' => '',
    'Сохранить настройки модуля' => '',
    'Страница настроек данного модуля недоступна!' => '',
    'Странцйа не найдена!' => '',
    'Текущая тема' => '',
    'Тема' => '',
    'Тема не используется' => '',
    'Темы оформления' => '',
    'У Вас активирован модуль "Установщик", после установки системы его необходимо отключить! <br/> <a href="http://www.yiiframework.ru/doc/guide/ru/basics.module">Подробнее про Yii модули</a>' => '',
    'Установлено модулей:' => '',
    'Файл {file} не существует или не доступен для записи!' => '',
    'Файл {file} не существует или не доступен для чтения!' => '',
    'версии' => '',
    'версия' => '',
);
