#!/usr/bin/env php
<?php

// change the following paths if necessary
$yiic = dirname(__FILE__) . '/vendor/framework/yiic.php';
$config = dirname(__FILE__) . '/protected/config/console.php';

require_once($yiic);