<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Please, {login} or {register} for commenting!' => 'Пожалуйста, {login} или {register} для комментирования!',
  'login' => 'авторизуйтесь',
  'register' => 'зарегистрируйтесь',
  'Guest can comment ?' => 'Гости могут комментировать ?',
  'reply' => 'ответить',
  '0.5' => '0.5',
  'Email' => 'Email',
  'Email for notifications' => 'Email для уведомлений?',
  'ID' => 'ID',
  'IP address' => 'IP адрес',
  'http://yupe.ru' => 'http://yupe.ru',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
  '{className}: Sending information about new site comment.' => '{className}: Отправляем информацию о создании нового комментария на сайте.',
  'Automatic comment confirmation' => 'Автоматическое подтверждение комментариев',
  'This section describes comment management' => 'В данном разделе представлены средства управления комментариями',
  'Do you really want to delete selected elements?' => 'Вы уверены, что хотите удалить выбранные элементы?',
  'Do you really want do remove comment?' => 'Вы уверены, что хотите удалить комментарий?',
  'Created at' => 'Дата создания',
  'Create comment' => 'Добавить комментарий',
  'Create comment and close' => 'Добавить комментарий и закрыть',
  'Create comment and continue' => 'Добавить комментарий и продолжить',
  'New post was created on site "{app}"!' => 'Добавлена новая запись на сайте "{app}"!',
  'Create' => 'Добавление',
  'Record was not added! Fill form correct!' => 'Запись не добавлена! Заполните форму корректно!',
  'Requested page was not found!' => 'Запрошенная страница не найдена!',
  'Name' => 'Имя',
  'Find comments' => 'Искать комментарии',
  'Verification code' => 'Код проверки',
  'RSS records count' => 'Количество записей в RSS',
  'Comments' => 'Комментариев',
  'Comments' => 'Комментарии',
  'Comments - show' => 'Комментарии - просмотр',
  'Comments - edit' => 'Комментарии - редактирование',
  'Comments - management' => 'Комментарии - управление',
  'Comment' => 'Комментарий',
  'Comment - create' => 'Комментарий - добавление',
  'Comment was created!' => 'Комментарий добавлен!',
  'Comment was updated!' => 'Комментарий обновлен!',
  'Content' => 'Контент',
  'Maximum captcha length' => 'Максимальная длинна капчи',
  'Minimum captcha length' => 'Минимальная длинна капчи',
  'Model' => 'Модель',
  'Comments moderation' => 'Модерация комментариев',
  'Module for simple comments support' => 'Модуль для простых комментариев',
  'Comment was created on your site:
Author: {author}
Model/ID: {model}/{model_id}
Comment text:  {comment}' =>   'На вашем сайте добавлен комментарий:
Автор: {author}
Модель/ID: {model}/{model_id}
Текст комментария: {comment}',
  'Captcha settings' => 'Настройки капчи',
  'Bad request. Please don\'t repeate similar requests anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
  'Module general settings' => 'Основные настройки модуля',
  'Please, set "model" and "modelId" for "{widget}" widget!' => 'Пожалуйста, укажите "model" и "modelId" для виджета "{widget}" !',
  'Find comments' => 'Поиск комментариев',
  'Show captcha for guests' => 'Показывать капчу для гостей',
  'Fields with' => 'Поля, отмеченные',
  'Menu items order' => 'Порядок следования в меню',
  'Accepted' => 'Принят',
  'Check' => 'Проверка',
  'Show comment' => 'Просмотр комментария',
  'View comment' => 'Просмотреть комментарий',
  'Accepted tags' => 'Разрешенные теги',
  'Edit' => 'Редактирование',
  'Edit comment' => 'Редактирование комментария',
  'Parent' => 'Родитель',
  'Site' => 'Сайт',
  'Save comment and close' => 'Сохранить комментарий и закрыть',
  'Save comment and continue' => 'Сохранить комментарий и продолжить',
  'Spam' => 'Спам',
  'You comments is in validation. Thanks.' => 'Спасибо, Ваша запись добавлена и ожидает проверки!',
  'You record was created. Thanks.' => 'Спасибо, Ваша запись добавлена!',
  'Comments list' => 'Список комментариев',
  'Status' => 'Статус',
  'Default comments status' => 'Статус комментариев по умолчанию',
  'Unknown status' => 'Статус неизвестен',
  'Text' => 'Текст',
  'Model type' => 'Тип модели',
  'You have {{count}} new comments. {{link}}' => 'У Вас {{count}} новых комментариев. {{link}}',
  'Notify about comment?' => 'Уведомить о новом комментарии?',
  'Deleted' => 'Удален',
  'Delete' => 'Удалить',
  'Delete comment' => 'Удалить комментарий',
  'Manage' => 'Управление',
  'Manage comments' => 'Управление комментариями',
  'create' => 'добавление',
  'are require.' => 'обязательны.',
  'manage' => 'управление',
  'Antispam interval' => 'Интервал (в секундах) для защиты от спама',
  'Spam protection, try to create comment after {few} seconds!'=>'Защита от спама, попробуйте добавить комментарий спустя {few} секнд!',
  'Last comments' => 'Последние комментарии',
  'Reply' => 'Ответить',
  'Be first!' => 'Станьте первым!',
  'There is an error when create comments, try again later.'=>'При добавлении комментария возникла ошибка, повторите попытку позже.',
  'WRITE COMMENT'=>' НАПИСАТЬ КОММЕНТАРИЙ',
  'From user' => 'От имени',
  'Insert symbols you see on picture'=>'Введите цифры указанные на картинке',
);
