<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Link' => 'Ссылка',
  '*unknown*' => '*неизвестно*',
  '--choose--' => '--выберите--',
  '0.4' => '0.4',
  'file' => 'file',
  'http://yupe.ru' => 'http://yupe.ru',
  'id' => 'id',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
  'Alternative text' => 'Альтернативный текст',
  'This section describes Image management functions' => 'В данном разделе представлены средства управления изображениями',
  'Do you really want to remove image?' => 'Вы уверены, что хотите удалить изображение?',
  'Gallery' => 'Галерея',
  'Main images category' => 'Главная категория изображений',
  'Created at' => 'Дата создания',
  'Directory "{dir}" is not accessible for writing ot not exists! {link}' => 'Директория "{dir}" не доступна для записи или не существует! {link}',
  'Creator' => 'Добавил',
  'Add image' => 'Добавить изображение',
  'Add image and save' => 'Добавить изображение и закрыть',
  'Add image and close' => 'Добавить изображение и продолжить',
  'Add' => 'Добавление',
  'Requested page was not found!' => 'Запрошенная страница не найдена!',
  'Change module settings' => 'Изменить настройки модуля',
  'Image' => 'Изображение',
  'Image created!' => 'Изображение добавлено!',
  'Image updated!' => 'Изображение обновлено!',
  'Image removed!' => 'Изображение удалено!',
  'Images' => 'Изображения',
  'Images - add' => 'Изображения - добавление',
  'Images - show' => 'Изображения - просмотр',
  'Images - edit' => 'Изображения - редактирование',
  'Images - manage' => 'Изображения - управление',
  'Find image' => 'Искать изображение',
  'Picture' => 'Картинка',
  'Directory for uploading images' => 'Каталог для загрузки изображений',
  'Category' => 'Категория',
  'Content' => 'Контент',
  'Maximum size (in bytes)' => 'Максимальный размер (в байтах)',
  'Minimum size (in bytes)' => 'Минимальный размер (в байтах)',
  'Gallery module is not installed' => 'Модуль галерей не установлен',
  'Module for images management' => 'Модуль для хранения изображений',
  'Title' => 'Название',
  'Bad request. Please don\'t repeat similar requests anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
  'Description' => 'Описание',
  'Please, choose catalog for images! {link}' => 'Пожалуйста, укажите каталог для хранения изображений! {link}',
  'Find images' => 'Поиск изображений',
  'Fields with' => 'Поля, отмеченные',
  'Preview' => 'Превью',
  'There is an error when adding new image =(' => 'При добавлении картинки в галерею произошла ошибка =(',
  'Show image' => 'Просмотр изображения',
  'View image' => 'Просмотреть изображение',
  'Allowed extensions (separated by comma)' => 'Разрешенные расширения (перечислите через запятую)',
  'Edit' => 'Редактирование',
  'Edit image' => 'Редактирование изображение',
  'Change image' => 'Редактирование изображения',
  'Parent' => 'Родитель',
  'Save mage and close' => 'Сохранить изображение и закрыть',
  'Save image and continue' => 'Сохранить изображение и продолжить',
  'Images list' => 'Список изображений',
  'Status' => 'Статус',
  'Image type' => 'Тип картинки',
  'Remove image' => 'Удалить изображение',
  'Set maximum images size {link}' => 'Укажите максимальный размер изображений {link}',
  'Management' => 'Управление',
  'Image management' => 'Управление изображениями',
  'File' => 'Файл',
  'add' => 'добавление',
  'allowed' => 'доступно',
  'are required.' => 'обязательны.',
  'need to be checked' => 'требуется проверка',
  'management' => 'управление',
);
