<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '--choose--' => '--выберите--',
  '--unknown--' => '--неизвестно--',
  '0.1' => '0.1',
  'ID' => 'ID',
  'MainEvent with "{code}" code was not found!' => 'MailEvent c кодом "{code}" не найден!',
  'MainEvent with code "{code}" don\'t contain any of active templates!' => 'MailEvent c кодом "{code}" не содержит ни одного активного шаблона!',
  'http://yupe.ru' => 'http://yupe.ru',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
  'This section contain mail messages management' => 'В данном разделе представлены средства управления почтовыми событиями',
  'This section contain mail message templates management' => 'В данном разделе представлены средства управления почтовыми шаблонами',
  'Do you really want to remove?' => 'Вы уверены, что хотите удалить?',
  'Create template' => 'Добавить  шаблон',
  'Create mail template' => 'Добавить почтвый шаблон',
  'Create event' => 'Добавить событие',
  'Create event and close' => 'Добавить событие и закрыть',
  'Create event and continue' => 'Добавить событие и продолжить',
  'Create template' => 'Добавить шаблон',
  'Create template and close' => 'Добавить шаблон и закрыть',
  'Create' => 'Добавление',
  'Event creation' => 'Добавление события',
  'Template creation' => 'Добавление шаблона',
  'Record was created!' => 'Запись добавлена!',
  'Record was updated!' => 'Запись обновлена!',
  'Record was removed!' => 'Запись удалена!',
  'Requested page was not found' => 'Запрошенная страница не найдена',
  'Requested page was not found.' => 'Запрошенная страница не найдена.',
  'Find' => 'Искать',
  'Component YMailMessage.mailComponent is not working!' => 'Компонент YMailMessage.mailComponent не работает!',
  'For' => 'Кому',
  'Module for mail message management' => 'Модуль управления почтовыми сообщениями',
  'Title' => 'Название',
  'Bad request. Please don\'t repeate similar request anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
  'Description' => 'Описание',
  'From' => 'От',
  'Error when sending mail!' => 'Ошибка отправка почты!',
  'Find mail messages' => 'Поиск почтовых событий',
  'Find mail templates' => 'Поиск почтовых шаблонов',
  'Fields, with' => 'Поля, отмеченные',
  'Mail events' => 'Почтовые события',
  'Mail messages' => 'Почтовые сообщения',
  'Mail templates' => 'Почтовые шаблоны',
  'View mail event' => 'Просмотр почтового события',
  'View mail template' => 'Просмотр почтового шаблона',
  'Show template' => 'Просмотреть событие',
  'View template' => 'Просмотреть шаблон',
  'Edit' => 'Редактирование',
  'Edit mail event' => 'Редактирование почтового события',
  'Edit mail message' => 'Редактирование почтового сообщения',
  'Edit mail template' => 'Редактирование почтового шаблона',
  'Edit event' => 'Редактирование события',
  'Edit template' => 'Редактирование шаблона',
  'Edit template ' => 'Редактирование шаблона ',
  'Services' => 'Сервисы',
  'Symbolic code' => 'Символьный код',
  'Event' => 'Событие',
  'Create template and continue' => 'Создать шаблон и продолжить',
  'Message' => 'Сообщение',
  'Save event and close' => 'Сохранить событие и закрыть',
  'Save event and continue' => 'Сохранить событие и продолжить',
  'Save template and close' => 'Сохранить шаблон и закрыть',
  'Save template and continue' => 'Сохранить шаблон и продолжить',
  'List' => 'Список',
  'Events list' => 'Список почтовых событий',
  'Mail templates list' => 'Список почтовых шаблонов',
  'Messages list' => 'Список событий',
  'Templates list' => 'Список шаблонов',
  'Status' => 'Статус',
  'Topic' => 'Тема',
  'Remove event' => 'Удалить  событие',
  'Remove template' => 'Удалить шаблон',
  'Management' => 'Управление',
  'Template with "{code}" was not found!' => 'Шаблон с кодом "{code}" не найден!',
  'Templates' => 'Шаблонов',
  'active' => 'активен',
  'adding' => 'добавление',
  'not active' => 'не активен',
  'are required.' => 'обязательны.',
  'management' => 'управление',
);
