<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Simple text'                                                                           => 'Простой текст',
    'Delete'                                                                                => 'Удалить',
    'Do you really want to delete selected elements?'                                       => 'Вы уверены, что хотите удалить выбранные элементы?',
    '*unknown type*'                                                                        => '*неизвестный тип*',
    '0.2'                                                                                   => '0.2',
    'Add block'                                                                             => 'Добавить блок',
    'Add block and close'                                                                   => 'Добавить блок и закрыть',
    'Add block and continue'                                                                => 'Добавить блок и продолжить',
    'Add content block'                                                                     => 'Добавить блок контента',
    'Add new content block'                                                                 => 'Добавить новый блок контента',
    'Adding new content block'                                                              => 'Добавление новый блок контента',
    'Administration'                                                                        => 'Управление',
    'Do you really want to delete content block?'                                           => 'Вы уверены, что хотите удалить блок контента?',
    'Do you really want to remove content block?'                                           => 'Вы уверены, что хотите удалить блок контента?',
    'Blocks list'                                                                           => 'Список блоков',
    'Code'                                                                                  => 'Код',
    'Category'                                                                              => 'Категория',
    'Content'                                                                               => 'Контент',
    'Content block'                                                                         => 'Блок контента',
    'Content block "{code}" was not found !'                                                => 'Контент блок "{code}" не найден !',
    'Group content block "{category_id}" was not found !'                                   => 'Группа контент блоков "{category_id}" не найдена !',
    'Content block was changed!'                                                            => 'Контент блок изменен!',
    'Blocks'                                                                                => 'Блоки',
    'Content blocks'                                                                        => 'Блоки контента',
    'Content blocks - add'                                                                  => 'Блоки контента - создание',
    'Content blocks - admin'                                                                => 'Блоки контента - управление',
    'Content blocks - edit'                                                                 => 'Блоки контента - редактирование',
    'Content blocks - view'                                                                 => 'Блоки контента - просмотр',
    'Content blocks administration'                                                         => 'Управление блоками контента',
    'Description'                                                                           => 'Описание',
    'Edit content block'                                                                    => 'Редактировать контент блок',
    'Executed PHP code'                                                                     => 'Исполняемый PHP код',
    'Fields with'                                                                           => 'Поля отмеченные',
    'Find block'                                                                            => 'Найти блок',
    'Find content blocks'                                                                   => 'Найти блоки контента',
    'Full text'                                                                             => 'Полный текст',
    'HTML code'                                                                             => 'HTML код',
    'Insert content block title for ContentBlockWidget!'                                    => 'Укажите название контент блока для ContentBlockWidget!',
    'Insert group content block title for ContentBlockGroupWidget!'                         => 'Укажите название группы контент блоков для ContentBlockGroupWidget!',
    'Module for create simple content blocks'                                               => 'Модуль для создания и редактирования произвольных блоков контента',
    'New content block was added!'                                                          => 'Новый контент блок добавлен!',
    'Page was not found!'                                                                   => 'Запрошенная страница не найдена!',
    'Remove content block'                                                                  => 'Удалить блок контента',
    'Save block and close'                                                                  => 'Сохранить блок и закрыть',
    'Save block and continue'                                                               => 'Сохранить блок и продолжить',
    'Shortcode for using this block in template:'                                           => 'Код для использования этого блока в шаблоне:',
    'Shortcode for using this block group in template:'                                     => 'Код для использования этого блока вместе с группой в шаблоне:',
    'This section presents content blocks management'                                       => 'В данном разделе представлены средства управления блоками контента',
    'Title'                                                                                 => 'Заголовок',
    'Type'                                                                                  => 'Тип',
    'Unknown field format "{attribute}" only alphas, digits and _, from 2 to 50 characters' => 'Неверный формат поля "{attribute}" допустимы только буквы, цифры и символ подчеркивания, от 2 до 50 символов',
    'Unknown request!'                                                                      => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!',
    'View content block'                                                                    => 'Просмотр блока контента',
    'add'                                                                                   => 'создание',
    'administration'                                                                        => 'управление',
    'are required.'                                                                         => 'обязательны для заполнения',
    'http://yupe.ru'                                                                        => 'http://yupe.ru',
    'id'                                                                                    => 'id',
    'team@yupe.ru'                                                                          => 'team@yupe.ru',
    'yupe team'                                                                             => 'yupe team',
    'Select {field}'                                                                        => 'Выберите {field}',
    'Manage blocks'                                                                         => 'Управление блоками',
    'Creating block'                                                                        => 'Создание блока',
    'Removing block'                                                                        => 'Удаление блока',
    'List of blocks'                                                                        => 'Просмотр списка блоков',
    'Editing blocks'                                                                        => 'Редактирование блока',
    'Viewing blocks'                                                                        => 'Просмотр блоков',
    'Raw text'                                                                              => 'Необработанный текст',
    '--choose--'                                                                            => '--выберите--',
    '--not selected--'                                                                      => '--не выбрана--',
    'Category "{category}" does not exist, please enter the unsettled category'             => 'Категория "{category}" не существует, введите пожалуйста сушествующую категорию',
    'Parameter Description:<br><ul><li>category - category code. Required paramert;</li><li>limit - how much of the output. Not obligatory paramert;</li><li>cacheTime - cache lifetime (as is frequently updated cache). Not obligatory paramert;</li><li>rand - determines how to display units, randomly or not. "true" or "false" (default "false").</li></ul>' => 'Описание параметров:<br><ul><li>category - код категории. Обязательный парамерт;</li><li>limit - какое количество блоков выводить. Не обязательный парамерт;</li><li>cacheTime - время жизни кэша (как часто обновляется кэш). Не обязательный парамерт;</li><li>rand - определяет как выводить блоки, рандомно или нет. (по умолчанию "false").</li></ul>'
);
