<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Enter'                                                          => 'Введите',
    'Error while saving record!'                                     => 'Ошибка при сохранении записи',
    'Model {class} does not have attribute "{attr}"'                 => 'Модель {class} не имеет аттрибута "{attr}"',
    'Model {class} not found by primary key "{pk}"'                  => 'Модель {class} имеющая первичный ключ "{pk}" не найдена ',
    'Model {class} rules do not allow to update attribute "{attr}"'  => 'Правила модели {class} не позволяют изменять данный аттрибут "{attr}"',
    'Property "attribute" should be defined.'                        => 'Свойство "attribute" должно быть определено',
    'Property "primaryKey" should be defined.'                       => 'Свойство "primaryKey" должно быть определено',
    'You should provide modelClass in constructor of EditableSaver.' => 'Вы должны объявить modelClass в конструкторе EditableSaver.',
];
