<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Cannot create more than one root in single root mode.'                              => 'Не возможно создать более одного корня в режиме "1 корень"',
    'Many roots mode is off.'                                                            => 'Режим со множеством корней отключен',
    'The node already is root node.'                                                     => 'Узел уже является коренным',
    'The node cannot be deleted because it is already deleted.'                          => 'Узел не может быть удален, т.к. уже является удаленным',
    'The node cannot be deleted because it is new.'                                      => 'Узел не может быть удален т.к. является новым узлом',
    'The node cannot be inserted because it is deleted.'                                 => 'Узел не может быть вставлен, т.к. удален',
    'The node cannot be inserted because it is not new.'                                 => 'Узел не может быть вставлен, т.к. является новым',
    'The node cannot be inserted because target node is deleted.'                        => 'Узел не может быть вставлен т.к. целевой узел удален.',
    'The node should not be deleted.'                                                    => 'Данный узел не должен быть удален',
    'The node should not be new record.'                                                 => 'Данный узел не должен быть новым',
    'The target node should not be deleted.'                                             => 'Целевой узел не должен быть удален',
    'The target node should not be descendant.'                                          => 'Целевой узел не должен быть зависимым',
    'The target node should not be root.'                                                => 'Целевой узел не должен быть корнем',
    'The target node should not be himself.'                                             => 'Целевой узел не должен быть самим собой :)',
    'You should not use CActiveRecord::delete() method when NestedSetBehavior attached.' => 'Не стоит использовать CActiveRecord::delete() при подключенном NestedSetBehavior',
    'You should not use CActiveRecord::save() method when NestedSetBehavior attached.'   => 'Не стоит использовать CActiveRecord::save() при подключенном NestedSetBehavior',
];
