<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Install'                                                            => 'Установка',
    'Creating module'                                                    => 'Создание модуля',
    '0.2'                                                                => '0.2',
    'IDE/Editors'                                                        => 'IDE/Редакторы',
    'YupeTeam'                                                           => 'YupeTeam',
    'ZendSearch'                                                         => 'ZendSearch',
    'http://yupe.ru'                                                     => 'http://yupe.ru',
    'team@yupe.ru'                                                       => 'team@yupe.ru',
    'Blogs'                                                              => 'Блоги',
    'Enable'                                                             => 'Включить',
    'Abilities'                                                          => 'Возможности',
    'Disable'                                                            => 'Выключить',
    'RSS feed generation'                                                => 'Генерация Feed-ленты',
    'Module for project documentation'                                   => 'Данный модуль предназначен для документирования проекта.',
    'Documentation'                                                      => 'Документация',
    'Using userspace settings'                                           => 'Использование настроек Userspace',
    'Pages caching on filtration level'                                  => 'Кеширование страниц на уровне фильтрации',
    'Team'                                                               => 'Команда',
    'ConfigManager component'                                            => 'Компонент ConfigManager',
    'Components'                                                         => 'Компоненты',
    'Memcached configuration'                                            => 'Конфигурация Memcached',
    'Local docs'                                                         => 'Локальная документация',
    'Migrator'                                                           => 'Мигратор',
    'Modules'                                                            => 'Модули',
    'Module for view and edit docs files (HTML and Markdown)'            => 'Модуль для просмотра и редактирования файлов документации (HTML и Markdown)',
    'Go home'                                                            => 'На сайт',
    'Writing docs'                                                       => 'Написание документации',
    'Files settings'                                                     => 'Настройки файлов',
    'Undefined title'                                                    => 'Не определён заголовок',
    'About Yupe!'                                                        => 'О Юпи!',
    'About module'                                                       => 'О модуле',
    'Curl wrapper'                                                       => 'Обертка над Curl',
    'Updated {mtime}'                                                    => 'Обновлено {mtime}',
    'Online docs'                                                        => 'Онлайн документация',
    'Methods description'                                                => 'Описание методов',
    'Optimal APC settings'                                               => 'Оптимальные настройки APC',
    'General module settings'                                            => 'Основные настройки модуля',
    'Show error'                                                         => 'Отображать ошибку',
    'Show page for language by default'                                  => 'Отображать страницу из языка поумолчанию',
    'Show error page if doc file in current language was not found?'     => 'Показывать страницу ошибки, если файл документации на данном языке не найден?',
    'Help project'                                                       => 'Помощь проекту',
    'Problems of CWebUser and Gii module'                                => 'Проблемы CWebUser и модуля Gii',
    'Show local files'                                                   => 'Просмотр локальных файлов',
    'Working in eclipse'                                                 => 'Работа с eclipse',
    'Development and support'                                            => 'Разработка и поддержка',
    'For developers'                                                     => 'Разработчику',
    'Docs files destination'                                             => 'Расположение файлов документации',
    'Modules docs files destination ({module} replaced by module title)' => 'Расположение файлов документации модулей ({module} вместо него подставляется название модуля)',
    'Extensions for HTML files'                                          => 'Расширения для файлов HTML',
    'Extensions for MarkDown files'                                      => 'Расширения для файлов MarkDown',
    'Docs page was not found'                                            => 'Страница документации не найдена',
    'Docs page was not found or it\'s empty'                             => 'Страница документации не найдена или пуста',
    'Existing files'                                                     => 'Существующие файлы',
    'Files'                                                              => 'Файлы',
    'Files need display in control panel'                                => 'Файлы, которые необходимо показать в админ панели',
    'Yupe!'                                                              => 'Юпи!',
    'Yupe! Documentation'                                                => 'Юпи! Документация',
    'Comment'                                                            => 'Комментарии',
    'Set testing environment'                                            => 'Настройка тестового окружения'
);
