<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '0.2' => '0.2',
    'Abilities' => 'Возможности',
    'About module' => 'О модуле',
    'About Yupe!' => 'О Юпи!',
    'Blogs' => 'Блоги',
    'Comment' => 'Комментарии',
    'Components' => 'Компоненты',
    'ConfigManager component' => 'Компонент ConfigManager',
    'Creating module' => 'Создание модуля',
    'Curl wrapper' => 'Обертка над Curl',
    'Development and support' => 'Разработка и поддержка',
    'Disable' => 'Выключить',
    'Docs files destination' => 'Расположение файлов документации',
    'Docs page was not found or it\'s empty' => 'Страница документации не найдена или пуста',
    'Docs page was not found' => 'Страница документации не найдена',
    'Documentation' => 'Документация',
    'Enable' => 'Включить',
    'Existing files' => 'Существующие файлы',
    'Extensions for HTML files' => 'Расширения для файлов HTML',
    'Extensions for MarkDown files' => 'Расширения для файлов MarkDown',
    'Files need display in control panel' => 'Файлы, которые необходимо показать в админ панели',
    'Files settings' => 'Настройки файлов',
    'Files' => 'Файлы',
    'For developers' => 'Разработчику',
    'General module settings' => 'Основные настройки модуля',
    'Go home' => 'На сайт',
    'Help project' => 'Помощь проекту',
    'http://yupe.ru' => 'http://yupe.ru',
    'IDE/Editors' => 'IDE/Редакторы',
    'Install' => 'Установка',
    'Local docs' => 'Локальная документация',
    'Memcached configuration' => 'Конфигурация Memcached',
    'Methods description' => 'Описание методов',
    'Migrator' => 'Мигратор',
    'Module for project documentation' => 'Данный модуль предназначен для документирования проекта.',
    'Module for view and edit docs files (HTML and Markdown)' => 'Модуль для просмотра и редактирования файлов документации (HTML и Markdown)',
    'Modules docs files destination ({module} replaced by module title)' => 'Расположение файлов документации модулей ({module} вместо него подставляется название модуля)',
    'Modules' => 'Модули',
    'Online docs' => 'Онлайн документация',
    'Optimal APC settings' => 'Оптимальные настройки APC',
    'Pages caching on filtration level' => 'Кеширование страниц на уровне фильтрации',
    'Problems of CWebUser and Gii module' => 'Проблемы CWebUser и модуля Gii',
    'RSS feed generation' => 'Генерация Feed-ленты',
    'Set testing environment' => 'Настройка тестового окружения',
    'Show error page if doc file in current language was not found?' => 'Показывать страницу ошибки, если файл документации на данном языке не найден?',
    'Show error' => 'Отображать ошибку',
    'Show local files' => 'Просмотр локальных файлов',
    'Show page for language by default' => 'Отображать страницу из языка поумолчанию',
    'Team' => 'Команда',
    'team@yupe.ru' => 'team@yupe.ru',
    'Undefined title' => 'Не определён заголовок',
    'Updated {mtime}' => 'Обновлено {mtime}',
    'Using userspace settings' => 'Использование настроек Userspace',
    'Working in eclipse' => 'Работа с eclipse',
    'Writing docs' => 'Написание документации',
    'Yupe! Documentation' => 'Юпи! Документация',
    'Yupe!' => 'Юпи!',
    'YupeTeam' => 'YupeTeam',
    'ZendSearch' => 'ZendSearch',
];
