<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '0.1' => '',
  'ID' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Ваша оценка' => '',
  'Голосование' => 'Vote',
  'Голосование за любой контент' => '',
  'Дата добавления' => '',
  'Добавил' => '',
  'Добавить голос' => '',
  'Добавление' => '',
  'Добавление голоса' => '',
  'Запрошенная страница не найдена!' => '',
  'Значение' => '',
  'Модель' => '',
  'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!' => '',
  'Оцените изображение' => '',
  'Поиск' => '',
  'Поля, отмеченные * обязательны для заполнения' => '',
  'Порядок следования в меню' => '',
  'Произошла ошибка!' => '',
  'Просмотр голоса' => '',
  'Просмотреть голос' => '',
  'Редактирование' => '',
  'Редактирование голоса' => '',
  'Редактировать голос' => '',
  'Сервисы' => '',
  'Сохранить голос' => '',
  'Страница не найдена!' => '',
  'Тип модели' => '',
  'Удалить голос' => '',
  'Укажите model и modelId для виджета VoteWidget!' => '',
  'Управление' => '',
  'Управление голосами' => '',
  'спасибо за голос!' => '',
);
