<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '*unknown*'                                                             => '',
    '--choose--'                                                            => '',
    '0.4'                                                                   => '',
    'file'                                                                  => '',
    'http://yupe.ru'                                                        => '',
    'id'                                                                    => '',
    'team@yupe.ru'                                                          => '',
    'yupe team'                                                             => '',
    'Alternative text'                                                      => '',
    'This section describes Image management functions'                     => '',
    'Do you really want to remove image?'                                   => '',
    'Gallery'                                                               => '',
    'Main images category'                                                  => '',
    'Created at'                                                            => '',
    'Directory "{dir}" is not accessible for writing ot not exists! {link}' => '',
    'Creator'                                                               => '',
    'Add image'                                                             => '',
    'Add image and save'                                                    => '',
    'Add image and close'                                                   => '',
    'Add'                                                                   => '',
    'Requested page was not found!'                                         => '',
    'Change module settings'                                                => '',
    'Image'                                                                 => '',
    'Image created!'                                                        => '',
    'Image updated!'                                                        => '',
    'Image removed!'                                                        => '',
    'Images'                                                                => '',
    'Images - add'                                                          => '',
    'Images - show'                                                         => '',
    'Images - edit'                                                         => '',
    'Images - manage'                                                       => '',
    'Find image'                                                            => '',
    'Picture'                                                               => '',
    'Directory for uploading images'                                        => '',
    'Category'                                                              => '',
    'Content'                                                               => '',
    'Maximum size (in bytes)'                                               => '',
    'Minimum size (in bytes)'                                               => '',
    'Gallery module is not installed'                                       => '',
    'Module for images management'                                          => '',
    'Title'                                                                 => '',
    'Bad request. Please don\'t repeat similar requests anymore'            => '',
    'Description'                                                           => '',
    'Please, choose catalog for images! {link}'                             => '',
    'Find images'                                                           => '',
    'Fields with'                                                           => '',
    'Preview'                                                               => '',
    'There is an error when adding new image =('                            => '',
    'Show image'                                                            => '',
    'View image'                                                            => '',
    'Allowed extensions (separated by comma)'                               => '',
    'Edit'                                                                  => '',
    'Edit image'                                                            => '',
    'Change image'                                                          => '',
    'Parent'                                                                => '',
    'Save mage and close'                                                   => '',
    'Save image and continue'                                               => '',
    'Images list'                                                           => '',
    'Status'                                                                => '',
    'Image type'                                                            => '',
    'Remove image'                                                          => '',
    'Set maximum images size {link}'                                        => '',
    'Management'                                                            => '',
    'Image management'                                                      => '',
    'File'                                                                  => '',
    'add'                                                                   => '',
    'allowed'                                                               => '',
    'are required.'                                                         => '',
    'need to be checked'                                                    => '',
    'management'                                                            => '',
];
