<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => '',
  'Application authorization manager must extend the RDbAuthManager class.' => '',
  'Application web user must extend the RWebUser class.' => '',
  'Error' => '',
  'Please try again or consult the documentation.' => '',
  'Congratulations!' => 'Complimenti!',
  'Install Rights' => 'Installa Rights',
  'No' => 'No',
  'Notice: All your existing data will be lost.' => 'Attenzione: Tutti i dati salvati andranno persi.',
  'Please confirm if you wish to reinstall.' => 'Per cortesia, conferma che intendi procedere nuovamente all\'installazione.',
  'Rights has been installed succesfully.' => 'Rights &egrave; stato installato.',
  'Rights is already installed!' => 'Rights &egrave; gi&agrave; installato!',
  'Yes' => 'S&igrave;',
  'You can start by generating your authorization items' => 'Puoi iniziare a generare le autorizzazioni',
  'You must be logged in to install Rights.' => 'Per installare Rights devi aver effettutato il login.',
  'here' => 'qui',
);
