<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
  'Congratulations!' => '祝贺！',
  'Install Rights' => '安装 Rights',
  'Installation failed.' => '安装失败。',
  'No' => '否',
  'Notice: All your existing data will be lost.' => '注意：所有存在的数据将会丢失。',
  'Please confirm if you wish to reinstall.' => '如果您希望重新安装，请确认。',
  'Rights has been installed succesfully.' => 'Rights 已经成功安装。',
  'Rights is already installed!' => 'Rights 已经安装过！',
  'Yes' => '是',
  'You can start by generating your authorization items' => '作为开始，您现在就可以生成授权项了！',
  'You must be logged in to install Rights.' => '您必须登录后才能安装 Rights。',
  'here' => '这里',

);
