<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '*unknown*' => '*неизвестно*',
  '--choose--' => '--выберите--',
  '0.3' => '0.3',
  'Id' => 'Id',
  'http://yupe.ru' => 'http://yupe.ru',
  'id' => 'id',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
  'This section describes image gallery management' => 'В данном разделе представлены средства управления галереями',
  'Visual Editor' => 'Визуальный редактор',
  'Vendor' => 'Владелец',
  'Images summary' => 'Всего изображений:',
  'Do you really want to remove gallery?' => 'Вы уверены, что хотите удалить галерею?',
  'Galleries' => 'Галереи',
  'Galleries - create' => 'Галереи - добавление',
  'Galleries - show' => 'Галереи - просмотр',
  'Galleries - edit' => 'Галереи - редактирование',
  'Galleries - manage' => 'Галереи - управление',
  'Image galleries' => 'Галереи изображений',
  'Gallery' => 'Галерея',
  'Created at' => 'Дата добавления',
  'Create gallery' => 'Добавить галерею',
  'Create gallery and close' => 'Добавить галерею и закрыть',
  'Create gallery and continue' => 'Добавить галерею и продолжить',
  'Create image' => 'Добавить изображение',
  'Add...' => 'Добавить...',
  'Adding' => 'Добавление',
  'Image adding' => 'Добавление изображения',
  'Record was created' => 'Запись добавлена!',
  'Record was updated' => 'Запись обновлена!',
  'Record was removed' => 'Запись удалена!',
  'Requested page was not found.' => 'Запрошенная страница не найдена.',
  'Image' => 'Изображение',
  'Image #{id} {result} deleted' => 'Изображение #{id} {result} удалено!',
  'Image #{id} edited' => 'Изображение #{id} отредактировано!',
  'Gallery images' => 'Изображения галереи',
  'Find gallery' => 'Искать галерею',
  'Content' => 'Контент',
  'Module for create simple image galleries' => 'Модуль для простых галерей изображений',
  'Title' => 'Название',
  'Start uploading' => 'Начать загрузку',
  'Bad request. Please don\'t repeat similar requests anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
  'Refresh image' => 'Обновить изображение',
  'Description' => 'Описание',
  'Cancel uploading' => 'Отменить загрузку',
  'Move images here' => 'Переместите сюда изображения',
  'Find galleries' => 'Поиск галерей',
  'Fields with' => 'Поля, отмеченные',
  'Menu items order' => 'Порядок следования в меню',
  'Show gallery' => 'Просмотр галереи',
  'View gallery' => 'Просмотреть галерею',
  'Edit' => 'Редактирование',
  'Edit gallery' => 'Редактирование галереи',
  'Edit image' => 'Редактирование изображения',
  'Edit image #{id}' => 'Редактирование изображения #{id}',
  'Save gallery and close' => 'Сохранить галерею и закрыть',
  'Save gallery and continue' => 'Сохранить галерею и продолжить',
  'Save image' => 'Сохранить изображение',
  'Galleries list' => 'Список галерей',
  'Status' => 'Статус',
  'Page was not found!' => 'Страница не найдена!',
  'Remove' => 'Удалить',
  'Remove gallery' => 'Удалить галерею',
  'Management' => 'Управление',
  'Gallery management' => 'Управление галереями',
  'Photo was created!' => 'Изображение добавлено!',
  'This is private gallery' => 'Это приватная галерея!',
  'create' => 'добавление',
  'my own' => 'личная',
  'not' => 'не',
  'are required.' => 'обязательны.',
  'private' => 'приватная',
  'public' => 'публичная',
  'hidden' => 'скрытая',
  'management' => 'управление',
  'success' => 'успешно',
  'Group adding' => 'Массовое добавление',
  'Update image'=>'Обновить изображение',
  'Image creation'=>'Добавление изображения',
  'Image edition'=>'Редактирование изображения',
  'Add image'=>'Добавить изображение',
  'Messages summary:'=>'Всего изображений:',
  'Edit message #{id}'=>'Редактирование изображения #{id}',
  'More...'=>'Подробнее...',
  'Images count' => 'Кол-во изображений'
);
