<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Catalog' => 'Каталог',
    'Andrey Opeykin' => 'Андрей Опейкин',
    'Home page' => 'Главная',
    'Main page management module' => 'Модуль для управления главной страницей',
    'Main settings' => 'Основные настройки',
    'Manage home page' => 'Настройка домашней страницы',
    'Page or post' => 'Страница или пост',
    'Page' => 'Страница',
    'Pages count' => 'Кол-во записей (только для постов)',
    'Pages' => 'Страницы',
    'Please activate "Blogs" or/and "Pages" module' => 'Активируйте модуль "блоги" и/или "страницы"',
    'Posts' => 'Посты',
    'read...' => 'читать...',
    'Records' => 'Записи',
    'Store' => 'Интернет-магазин',
    'Structure' => 'Структура',
    'Whats will be displayed' => 'Что отображать',
    'Yupe!' => 'Юпи!',
];
