<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Please activate "Blogs" or/and "Pages" module' => '请激活"博客"或"页面"模块',
    'Andrey Opeykin'                                => 'Boon Xiong',
    'Home page'                                     => '主页',
    'Pages count'                                   => '页面数量',
    'Main page management module'                   => '主页管理模块',
    'Posts'                                         => '文章',
    'Page'                                          => '页面',
    'Page or post'                                  => '页面或文章',
    'Whats will be displayed'                       => '将要显示的',
    'Yupe!'                                         => '内容',
    'Records'                                       => '记录',
    'Pages'                                         => '页面',
    'read...'                                       => '更多...',
];
