<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '*unknown*'                                                                     => '',
    '--choose--'                                                                    => '--选择--',
    '--no--'                                                                        => '--否--',
    '0.5'                                                                           => '',
    'Id'                                                                            => '',
    'http://yupe.ru'                                                                => '',
    'team@yupe.ru'                                                                  => '',
    'yupe team'                                                                     => '木星团队',
    'Alias'                                                                         => '别名',
    'This section describes category management'                                    => '这个版块提供分类管理',
    'You are adding translate in to {lang}!'                                        => '',
    'Do you really want to remove category?'                                        => '你确定要删除分类？',
    'Directory "{dir}" is available for write! {link}'                              => '',
    'Create category'                                                               => '创建分类',
    'Create category and close'                                                     => '创建分类并关闭',
    'Create category and continue'                                                  => '创建分类并继续',
    'Add translate in to {lang}'                                                    => '',
    'Create'                                                                        => '创建',
    'Record was created!'                                                           => '记录已经创建！',
    'Bad characters in {attribute} field'                                           => '',
    'Page was not found!'                                                           => '页面未找到！',
    'Change settings'                                                               => '修改设置',
    'Image'                                                                         => '图像',
    'Find category'                                                                 => '查找分类',
    'File uploading catalog (relatively Yii::app()->getModule("yupe")->uploadPath)' => '',
    'Categories'                                                                    => '分类',
    'Categories - show'                                                             => '分类 - 查看',
    'Categories - edit'                                                             => '分类 - 编辑',
    'Categories - manage'                                                           => '分类 - 管理',
    'Categories/Sections'                                                           => '分类/版块',
    'Category'                                                                      => '分类',
    'Categories - create'                                                           => '分类 - 创建',
    'Category was changed!'                                                         => '分类已经修改！',
    'Short description'                                                             => '简要说明',
    'Module for categories/sections management'                                     => '用于分类和版块管理的模块',
    'On moderation'                                                                 => '',
    'Title'                                                                         => '标题',
    'Bad request. Please don\'t use similar requests anymore'                       => '',
    'Description'                                                                   => '描述',
    'Published'                                                                     => '已发布',
    'Find category'                                                                 => '查找分类',
    'Fields with'                                                                   => '字段带有',
    'Menu items order'                                                              => '菜单项排序',
    'Show category'                                                                 => '查看分类',
    'View category'                                                                 => '查看分类',
    'Change'                                                                        => '更改',
    'Change category'                                                               => '更改分类',
    'Change translation in to {lang}'                                               => '更改语言为 {lang}',
    'Parent'                                                                        => '父项',
    'Save category and close'                                                       => '保存分类并关闭',
    'Save category and continue'                                                    => '保存分类并继续',
    'Categories list'                                                               => '分类列表',
    'Status'                                                                        => '状态',
    'Structure'                                                                     => '结构',
    'Remove category'                                                               => '删除分类',
    'Manage'                                                                        => '管理',
    'Category manage'                                                               => '分类管理',
    'Targeting category was not found!'                                             => '',
    'Draft'                                                                         => '草稿',
    'Language'                                                                      => '语言',
    'Language was not found!'                                                       => '语言未找到！',
    'create'                                                                        => '创建',
    'are required'                                                                  => '是必填项',
    'manage'                                                                        => '管理',
];
