<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '--choose--'                                                           => '--选择--',
    '--unknown--'                                                          => '--未知--',
    '0.1'                                                                  => '0.1',
    'ID'                                                                   => '',
    'MainEvent with "{code}" code was not found!'                          => '',
    'MainEvent with code "{code}" don\'t contain any of active templates!' => '',
    'http://yupe.ru'                                                       => '',
    'team@yupe.ru'                                                         => '',
    'yupe team'                                                            => '木星团队',
    'This section contain mail messages management'                        => '这个版块提供邮件管理功能',
    'This section contain mail message templates management'               => '这个版块提供邮件模板管理功能',
    'Do you really want to remove?'                                        => '你确定要删除？',
    'Create template'                                                      => '创建模板',
    'Create mail template'                                                 => '创建邮件模板',
    'Create event'                                                         => '创建事件',
    'Create event and close'                                               => '创建事件并关闭',
    'Create event and continue'                                            => '创建事件并继续',
    'Create template'                                                      => '创建模板',
    'Create template and close'                                            => '创建模板并关闭',
    'Create'                                                               => '创建',
    'Event creation'                                                       => '创建事件',
    'Template creation'                                                    => '创建模板',
    'Record was created!'                                                  => '记录已创建!',
    'Record was updated!'                                                  => '记录已更新！',
    'Record was removed!'                                                  => '记录已删除！',
    'Requested page was not found'                                         => '请求的页面未找到',
    'Requested page was not found.'                                        => '请求的页面未找到。',
    'Find'                                                                 => '查找',
    'Component YMailMessage.mailComponent is not working!'                 => '',
    'For'                                                                  => '为',
    'Module for mail message management'                                   => '电子邮件管理模块',
    'Title'                                                                => '标题',
    'Bad request. Please don\'t repeate similar request anymore'           => '',
    'Description'                                                          => '描述',
    'From'                                                                 => '来自',
    'Error when sending mail!'                                             => '发送邮件时遇到错误！',
    'Find mail messages'                                                   => '查找邮件消息',
    'Find mail templates'                                                  => '查找邮件模板',
    'Fields, with'                                                         => '字段带有',
    'Mail events'                                                          => '邮件事件',
    'Mail messages'                                                        => '邮件消息',
    'Mail templates'                                                       => '邮件模板',
    'View mail event'                                                      => '查看邮件事件',
    'View mail template'                                                   => '查看邮件模板',
    'Show template'                                                        => '查看模板',
    'View template'                                                        => '查看模板',
    'Edit'                                                                 => '编辑',
    'Edit mail event'                                                      => '编辑邮件事件',
    'Edit mail message'                                                    => '编辑邮件消息',
    'Edit mail template'                                                   => '编辑邮件模板',
    'Edit event'                                                           => '编辑事件',
    'Edit template'                                                        => '编辑模板',
    'Edit template '                                                       => '编辑模板 ',
    'Services'                                                             => '服务',
    'Symbolic code'                                                        => '代码',
    'Event'                                                                => '事件',
    'Create template and continue'                                         => '创建模板并继续',
    'Message'                                                              => '消息',
    'Save event and close'                                                 => '保存事件并关闭',
    'Save event and continue'                                              => '保存事件并继续',
    'Save template and close'                                              => '保存模板并关闭',
    'Save template and continue'                                           => '保存模板并继续',
    'List'                                                                 => '列表',
    'Events list'                                                          => '事件列表',
    'Mail templates list'                                                  => '邮件模板列表',
    'Messages list'                                                        => '消息列表',
    'Templates list'                                                       => '模板列表',
    'Status'                                                               => '状态',
    'Topic'                                                                => '主题',
    'Remove event'                                                         => '删除事件',
    'Remove template'                                                      => '删除模板',
    'Management'                                                           => '管理',
    'Template with "{code}" was not found!'                                => '"{code}" 模板未找到！',
    'Templates'                                                            => '模板',
    'active'                                                               => '激活',
    'adding'                                                               => '添加',
    'not active'                                                           => '未激活',
    'are required.'                                                        => '是必填项。',
    'management'                                                           => '管理',
    'Visual editor'                                                        => '可视化编辑器',
    'Menu items order'                                                     => '菜单项排序',
];
