<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '*unknown type*' => '',
  '0.2' => '',
  'Add block' => '',
  'Add block and close' => '',
  'Add block and continue' => '',
  'Add content block' => '',
  'Add new content block' => '',
  'Adding new content block' => '',
  'Administration' => '',
  'Do you really want to delete content block?' => '',
  'Do you really want to remove content block?' => '',
  'Blocks list' => '',
  'Code' => '',
  'Content' => '',
  'Content block' => '',
  'Content block "{code}" was not found !' => '',
  'Content block was changed!' => '',
  'Content blocks' => '',
  'Content blocks - add' => '',
  'Content blocks - admin' => '',
  'Content blocks - edit' => '',
  'Content blocks - view' => '',
  'Content blocks administration' => '',
  'Description' => '',
  'Edit content block' => '',
  'Executed PHP code' => '',
  'Fields with' => '',
  'Find block' => '',
  'Find content blocks' => '',
  'Full text' => '',
  'HTML code' => '',
  'Insert content block title for ContentBlockWidget!' => '',
  'Module for create simple content blocks' => '',
  'New content block was added!' => '',
  'Page was not found!' => '',
  'Remove Content block' => '',
  'Remove content block' => '',
  'Save block and close' => '',
  'Save block and continue' => '',
  'Shortcode for using this block in template:' => '',
  'This section presents content blocks management' => '',
  'Title' => '',
  'Type' => '',
  'Unknown field format "{attribute}" only alphas, digits and _, from 2 to 50 characters' => '',
  'Unknown request!' => '',
  'View Content block' => '',
  'View content block' => '',
  'add' => '',
  'administration' => '',
  'are required.' => '',
  'http://yupe.ru' => '',
  'id' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
);
