<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '0.1' => '',
  'Curl обёртка для Yii framework' => '',
  'IDE/Редакторы' => '',
  'YupeTeam' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'Блоги' => '',
  'В помощь разработчикам' => '',
  'Включить' => '',
  'Возможности' => '',
  'Выключить' => '',
  'Генерация Feed-ленты' => '',
  'Данный модуль предназначен для документирования проекта.' => '',
  'Документация' => 'Docs',
  'Кеширование страниц на уровне фильтрации' => '',
  'Команда' => '',
  'Компонент "Мигратор"' => '',
  'Методы компонента "Мигратор"' => '',
  'Модули' => '',
  'Модуль для просмотра и редактирования файлов документации (HTML и Markdown)' => '',
  'Написание документации' => '',
  'Настройки файлов' => '',
  'Не определён заголовок' => '',
  'О Юпи!' => '',
  'О модуле' => '',
  'Оптимальные настройки APC' => '',
  'Основные настройки модуля' => '',
  'Отображать ошибку' => '',
  'Отображать страницу из языка поумолчанию' => '',
  'Показывать страницу ошибки, если файл документации на данном языке не найден?' => '',
  'Помощь проекту' => '',
  'Работа с eclipse' => '',
  'Расположение файлов документации' => '',
  'Расположение файлов документации модулей ({module} вместо него подставляется название модуля)' => '',
  'Расширения для файлов HMTML' => '',
  'Расширения для файлов MarkDown' => '',
  'Существующие файлы' => '',
  'Файлы' => '',
  'Файлы, которые необходимо показать в админ панели' => '',
  'Юпи!' => '',
  'Юпи! Документация' => '',
  'изменено {mtime}' => '',
);
