<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '0.1' => '',
  'Curl обёртка для Yii framework' => '',
  'IDE/Редакторы' => 'IDE / Editors',
  'YupeTeam' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'Блоги' => 'Blogs',
  'В помощь разработчикам' => '',
  'Включить' => 'Enable',
  'Возможности' => 'Capabilities',
  'Выключить' => 'Disable',
  'Генерация Feed-ленты' => '',
  'Данный модуль предназначен для документирования проекта.' => 'This module is designed to document the Yupe.',
  'Документация' => 'Docs',
  'Кеширование страниц на уровне фильтрации' => '',
  'Команда' => 'Team',
  'Компонент "Мигратор"' => '',
  'Методы компонента "Мигратор"' => '',
  'Модули' => 'Modules',
  'Модуль для просмотра и редактирования файлов документации (HTML и Markdown)' => '',
  'Написание документации' => '',
  'Настройки файлов' => 'File settings',
  'Не определён заголовок' => '',
  'О Юпи!' => 'About Yupe',
  'О модуле' => 'About module',
  'Оптимальные настройки APC' => '',
  'Основные настройки модуля' => 'Basic Module Configuration',
  'Отображать ошибку' => '',
  'Отображать страницу из языка поумолчанию' => '',
  'Показывать страницу ошибки, если файл документации на данном языке не найден?' => '',
  'Помощь проекту' => '',
  'Работа с eclipse' => '',
  'Расположение файлов документации' => 'The location of documentation files',
  'Расположение файлов документации модулей ({module} вместо него подставляется название модуля)' => '',
  'Расширения для файлов HTML' => 'File extensions HTML',
  'Расширения для файлов MarkDown' => 'File extensions MarkDown',
  'Существующие файлы' => 'Existing files',
  'Файлы' => 'Files',
  'Файлы, которые необходимо показать в админ панели' => 'Files you want to show in the admin panel',
  'Юпи!' => 'Yupe!',
  'Юпи! Документация' => 'Yupe! Docs',
  'изменено {mtime}' => 'changed {mtime}',
);
