<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '0.2'                                                                       => '',
    'WebAction webstudio'                                                       => '',
    'http://webaction.su'                                                       => '',
    'info@webaction.su'                                                         => '',
    'For index creation, please click button below.'                            => '',
    'Index is updating... Wait please...'                                       => '',
    'Index updated successfully!'                                               => '',
    'Models you want to index is necessary to describe in configuration file.'  => '',
    'Find module in terms of Zend Lucene'                                       => '',
    'Update find index'                                                         => '',
    'Index data folder.'                                                        => '',
    'Wait please...'                                                            => '',
    'Find (Zend)'                                                               => '',
    'Find (Zend) - manage'                                                      => '',
    'There is an error!'                                                        => '',
    'Services'                                                                  => '',
    'Page was not found!'                                                       => '',
    'Manage'                                                                    => '',
    'manage'                                                                    => '',
    'Find!'                                                                     => '',
    'Search...'                                                                 => '',
    'Search by request: '                                                       => '',
    'Results:'                                                                  => '',
    'Nothing was found'                                                         => '',
    'Update config file or module, Module index not found for model "{model}"!' => '',
    'Module "{module}" not installed!'                                          => '',
    'This module require "Iconv" extension!'                                    => '',
];
