<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Enter'                                                          => 'Введіть',
    'Error while saving record!'                                     => 'Помилка під час збереження запису',
    'Model {class} does not have attribute "{attr}"'                 => 'Модель {class} не має атрибуту "{attr}"',
    'Model {class} not found by primary key "{pk}"'                  => 'Модель {class}, що має первинний ключ "{pk}" не знайдено ',
    'Model {class} rules do not allow to update attribute "{attr}"'  => 'Правило моделі {class} не дозволяють змінювати вказаний атрибут "{attr}"',
    'Property "attribute" should be defined.'                        => 'Властивість "attribute" повинно бути вказано',
    'Property "primaryKey" should be defined.'                       => 'Властивість "primaryKey" повинно бути вказано',
    'You should provide modelClass in constructor of EditableSaver.' => 'Ви мусите вказати modelClass в конструкторі EditableSaver.',
];
