<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Feed version not supported'                                                                   => 'Версії стрічки не підтримуються',
    'For RSS 1.0 specifications link element should be add per item'                               => 'В спецификації RSS 1.0 елемент повинен будети додадний для кожної сутоності',
    'Link Element is not set and it is required for RSS 1.0 to be used as about attribute of item' => 'Link Element не встановлено. Вказаний елемент обов´язковий для стандарту RSS 1.0',
    'No feed items configured'                                                                     => 'Сутності не налаштовані',
    'No items have been set'                                                                       => 'Сутності не встановлені',
];
