<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Cannot create more than one root in single root mode.'                              => 'Не можливо створювати більше аніж один корінь в режимі "1 корінь"',
    'Many roots mode is off.'                                                            => 'Режим із багатьма коренями вимкнуто',
    'The node already is root node.'                                                     => 'Вузол вже є корінним',
    'The node cannot be deleted because it is already deleted.'                          => 'Вузол не може бути вилученний, так як вже уже є видаленим',
    'The node cannot be deleted because it is new.'                                      => 'Вузол не може бути вилученний, так як є новим вузлом',
    'The node cannot be inserted because it is deleted.'                                 => 'Вузол не може бути вставлено, так як вже вилучений',
    'The node cannot be inserted because it is not new.'                                 => 'Узел не может быть вставлен, т.к. является новым',
    'The node cannot be inserted because target node is deleted.'                        => 'Узел не может быть вставлен т.к. целевой узел удален.',
    'The node should not be deleted.'                                                    => 'Вказанний вузол не можна видалити',
    'The node should not be new record.'                                                 => 'Вказаний вузол не повинен бути новим',
    'The target node should not be deleted.'                                             => 'Цільовий вузол не можна вулучити',
    'The target node should not be descendant.'                                          => 'Цільовий вузол не повинен бути залежним',
    'The target node should not be root.'                                                => 'Цільовий вузол не повинен бути корінним',
    'The target node should not be self.'                                                => 'Цільовий вузол не повинен бути самим собою :)',
    'You should not use CActiveRecord::delete() method when NestedSetBehavior attached.' => 'Не бажано використовувати CActiveRecord::delete() під час користування NestedSetBehavior',
    'You should not use CActiveRecord::save() method when NestedSetBehavior attached.'   => 'Не бажано використовувати CActiveRecord::save() під час користування NestedSetBehavior',
];
