<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Application authorization manager must extend the RightsAuthManager class.' => 'アプリケーションの権限マネージャは、RightsAuthManager クラスを継承しなければなりません。',
  'Application web user must extend the RightsWebUser class.' => 'アプリケーションのウェブ・ユーザーは、RightsWebUser クラスを継承しなければなりません。',
  'Congratulations!' => 'おめでとうございます。',
  'Install Rights' => 'Rights をインストールする',
  'Installation failed.' => 'インストールが失敗しました。',
  'No' => 'いいえ',
  'Notice: All your existing data will be lost.' => '注意 : 既存のデータは全て失われます。',
  'Please confirm if you wish to reinstall.' => '再インストールします。よろしいですか。',
  'Rights has been installed succesfully.' => 'Rights のインストールが成功しました。',
  'Rights is already installed!' => 'Rights は既にインストール済みです。',
  'Yes' => 'はい',
  'You can start by generating your authorization items' => '権限アイテムを生成して、権限の管理を開始することが出来ます。',
  'You must be logged in to install Rights.' => 'Rights をインストールするためには、ログインする必要があります。',
  'here' => 'こちら',
);
