<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '*unknown*'                                                   => '',
    '0.2'                                                         => '',
    'id'                                                          => '',
    'team@yupe.ru'                                                => '',
    'yupe team'                                                   => '',
    'Active'                                                      => '',
    'This section describes dictionary items management'          => '',
    'This section describes dictionary management'                => '',
    'Do you really want do delete dictionary item?'               => '',
    'Do you really want do delete dictionary?'                    => '',
    'Yes'                                                         => '',
    'Updated at'                                                  => '',
    'Updated at.'                                                 => '',
    'Created at'                                                  => '',
    'Create item'                                                 => '',
    'Create item and close'                                       => '',
    'Create item and continue'                                    => '',
    'Create dictionary'                                           => '',
    'Create dictionary and close'                                 => '',
    'Create dictionary and continue'                              => '',
    'Create'                                                      => '',
    'Dictionary crate'                                            => '',
    'Records'                                                     => '',
    'Record was created'                                          => '',
    'Requested page was not found'                                => '',
    'Item'                                                        => '',
    'Dictionary item'                                             => '',
    'Items'                                                       => '',
    'Dictionary items'                                            => '',
    'Dictionary items - create'                                   => '',
    'Dictionary items - show'                                     => '',
    'Dictionary items - edit'                                     => '',
    'Dictionary items - management'                               => '',
    'Updated by'                                                  => '',
    'Fund dictionary item'                                        => '',
    'Find dictionary'                                             => '',
    'Code'                                                        => '',
    'Module for simple dictionary'                                => '',
    'Title'                                                       => '',
    'Bad request. Please don\'t repeate similar requests anymore' => '',
    'No'                                                          => '',
    'Updated by.'                                                 => '',
    'Description'                                                 => '',
    'Find dictionariy items'                                      => '',
    'Find dictionary'                                             => '',
    'Fields with'                                                 => '',
    'Menu items order'                                            => '',
    'Show dictionary items'                                       => '',
    'Show dictionary'                                             => '',
    'Show dictionary item'                                        => '',
    'Show dictionary'                                             => '',
    'Edit'                                                        => '',
    'Edit dictionary item'                                        => '',
    'Edit dictionary items'                                       => '',
    'Edit dictionary'                                             => '',
    'Created by.'                                                 => '',
    'Save value and close'                                        => '',
    'Save value and continue'                                     => '',
    'Save dictionary and close'                                   => '',
    'Save dictionary and continue'                                => '',
    'Items list'                                                  => '',
    'Dictionaries list'                                           => '',
    'Dictionary'                                                  => '',
    'Dictionaries'                                                => '',
    'Dictionaries - create'                                       => '',
    'Dictionaries - show'                                         => '',
    'Dictionaries - edit'                                         => '',
    'Dictionaries - manage'                                       => '',
    'Structure'                                                   => '',
    'Remove dictionary item'                                      => '',
    'Remove dictionary'                                           => '',
    'Management'                                                  => '',
    'Dictionaries management'                                     => '',
    'create'                                                      => '',
    'are required.'                                               => '',
    'management'                                                  => '',
    'Record was added!'                                           => '',
    'Record was removed!'                                         => '',
    'Record was updated!'                                         => '',
    'Select {field}'                                              => '',
];
