<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    '*unknown*'                                                                      => '',
    '--choose--'                                                                     => '',
    '0.2'                                                                            => '',
    'Accepted extensions (separated by comma)'                                       => '',
    'Active'                                                                         => '',
    'Add a product'                                                                  => '',
    'Add product and close'                                                          => '',
    'Add product and continue'                                                       => '',
    'Added'                                                                          => '',
    'Manage'                                                                         => '',
    'Alias'                                                                          => '',
    'Do you really want to remove product?'                                          => '',
    'Article'                                                                        => '',
    'File uploads directory (relative to Yii::app()->getModule("yupe")->uploadPath)' => '',
    'Category'                                                                       => '',
    'Change settings'                                                                => '',
    'Content'                                                                        => '',
    'Creating'                                                                       => '',
    'Data'                                                                           => '',
    'Delete product'                                                                 => '',
    'Description'                                                                    => '',
    'Directory "{dir}" is not writeable! {link}'                                     => '',
    'Update product'                                                                 => '',
    'Edited'                                                                         => '',
    'Edition'                                                                        => '',
    'Editor'                                                                         => '',
    'Fields marked with'                                                             => '',
    'Find a product'                                                                 => '',
    'Find products'                                                                  => '',
    'ID'                                                                             => '',
    'Illegal characters in {attribute}'                                              => '',
    'Image'                                                                          => '',
    'Main category of products'                                                      => '',
    'Maximum size (in bytes)'                                                        => '',
    'Menu items order'                                                               => '',
    'Minimum size (in bytes)'                                                        => '',
    'This module allows creating a simple product catalog'                           => '',
    'No'                                                                             => '',
    'Not active'                                                                     => '',
    'Not available'                                                                  => '',
    'Page was not found!'                                                            => '',
    'Price'                                                                          => '',
    'Product'                                                                        => '',
    'Product show'                                                                   => '',
    'Product was not found!'                                                         => '',
    'Products'                                                                       => '',
    'Manage products'                                                                => '',
    'Products - creating'                                                            => '',
    'Products - edition'                                                             => '',
    'Products - view'                                                                => '',
    'Product admin'                                                                  => '',
    'Products administration'                                                        => '',
    'Product catalog'                                                                => '',
    'Product list'                                                                   => '',
    'Record was added!'                                                              => '',
    'Record was removed!'                                                            => '',
    'Record was updated!'                                                            => '',
    'Remove product'                                                                 => '',
    'Save product and close'                                                         => '',
    'Save product and continue'                                                      => '',
    'Short description'                                                              => '',
    'Special'                                                                        => '',
    'Status'                                                                         => '',
    'This section describes products manager'                                        => '',
    'Title'                                                                          => '',
    'Unknown request. Don\'t repeat it please!'                                      => '',
    'Updated'                                                                        => '',
    'User'                                                                           => '',
    'Show product'                                                                   => '',
    'Visual editor'                                                                  => '',
    'Yes'                                                                            => '',
    'administration'                                                                 => '',
    'creating'                                                                       => '',
    'http://yupe.ru'                                                                 => '',
    'are required.'                                                                  => '',
    'team@yupe.ru'                                                                   => '',
    'yupe team'                                                                      => '',
    'Constant link'                                                                  => '',
    'Select {field}'                                                                 => '',
);
