<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '*unknown*' => '',
  '--choose--' => '',
  '0.2' => '',
  'Accepted extensions (separated by comma)' => '',
  'Active' => '',
  'Add product' => '',
  'Add product and close' => '',
  'Add product and continue' => '',
  'Added' => '',
  'Administration' => '',
  'Alias' => '',
  'Do you really want to remove product?' => '',
  'Article' => '',
  'Catalog for file uploads (relatively Yii::app()->getModule("yupe")->uploadPath)' => '',
  'Category' => '',
  'Change settings' => '',
  'Content' => '',
  'Creating' => '',
  'Data' => '',
  'Delete product' => '',
  'Description' => '',
  'Directory "{dir}" is not accessible for write! {link}' => '',
  'Update product' => '',
  'Edited' => '',
  'Edition' => '',
  'Editor' => '',
  'Fields with' => '',
  'Find product' => '',
  'Find products' => '',
  'ID' => '',
  'Illegal characters in {attribute}' => '',
  'Image' => '',
  'Main category of products' => '',
  'Maximum size (in bytes)' => '',
  'Menu items order' => '',
  'Minimum size (in bytes)' => '',
  'Module for creating simple products catalog' => '',
  'No' => '',
  'Not active' => '',
  'Not available' => '',
  'Page was not found!' => '',
  'Price' => '',
  'Product' => '',
  'Product show' => '',
  'Product was not found!' => '',
  'Products' => '',
  'Products - administration' => '',
  'Products - creating' => '',
  'Products - edition' => '',
  'Products - view' => '',
  'Products admin' => '',
  'Products administration' => '',
  'Products catalog' => '',
  'Products list' => '',
  'Record was added!' => '',
  'Record was removed!' => '',
  'Record was updated!' => '',
  'Remove product' => '',
  'Save product and close' => '',
  'Save product and continue' => '',
  'Short description' => '',
  'Special' => '',
  'Status' => '',
  'This section describes products manager' => '',
  'Title' => '',
  'Unknown request. Don\'t use this request aymore!' => '',
  'Updated' => '',
  'User' => '',
  'Show product' => '',
  'Visual editor' => '',
  'Yes' => '',
  'administration' => '',
  'creating' => '',
  'http://yupe.ru' => '',
  'is required.' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'Constant link' => '',
);
