<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '-unknown-' => '-неизвестно-',
    '0.1' => '0.1',
    'are required' => 'обязательны.',
    'Bad request. Please don\'t repeat similar requests anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
    'CDbQueue.connectionId "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbQueue.connectionId "{id}" не верно. Пожалуйста буедитесь что вы ссылаетесь на верный ID компонента CDbConnection.',
    'Clean queue' => 'Очистить очередь',
    'Completed' => 'Выполнена',
    'Completing' => 'Завершение',
    'Create task and close' => 'Добавить задание и закрыть',
    'Create task and continue' => 'Добавить задание и продолжить',
    'Create task' => 'Добавить задание',
    'Created at' => 'Создано',
    'Creating queue' => 'Создание задания в очереди',
    'Creation' => 'Добавление',
    'creation' => 'добавление',
    'Delete' => 'Удалить',
    'Do you really want to delete selected elements?' => 'Вы уверены, что хотите удалить выбранные элементы?',
    'Do you really want to delete?' => 'Вы уверены, что хотите удалить?',
    'Edit task' => 'Редактирование задания',
    'Edit task.' => 'Редактировать задание',
    'Edit' => 'Редактирование',
    'Editing queue' => 'Редактирование задания очереди',
    'Error json_encode !' => 'Ошибка json_encode!',
    'Error' => 'Ошибка',
    'Fields with' => 'Поля, отмеченные',
    'Find task' => 'Искать задание',
    'Find tasks' => 'Поиск заданий',
    'Handler' => 'Обработчик',
    'High' => 'Высокий',
    'http://yupe.ru' => 'http://yupe.ru',
    'ID' => 'ID',
    'List of queue' => 'Просмотр списка заданий очереди',
    'Low' => 'Низкий',
    'Manage queue' => 'Управление очередями заданий',
    'Management' => 'Управление',
    'management' => 'управление',
    'New' => 'Новая',
    'Normal' => 'Нормальный',
    'Notice' => 'Примечание',
    'Priority' => 'Приоритет',
    'Queue cleaned!' => 'Очередь очищена!',
    'Record was created!' => 'Запись добавлена!',
    'Record was removed!' => 'Запись удалена!',
    'Record was updated!' => 'Запись обновлена!',
    'Remove task' => 'Удалить задание',
    'Removing queue' => 'Удаление задания из очереди',
    'Requested page was not found.' => 'Запрошенная страница не найдена.',
    'Save blog and close' => 'Сохранить блог и закрыть',
    'Save task' => 'Сохранить задание',
    'Services' => 'Сервисы',
    'Show task' => 'Просмотреть задание',
    'Start' => 'Начало',
    'Status' => 'Статус',
    'Task creation' => 'Добавить задание',
    'Task list' => 'Список заданий',
    'Task' => 'Задание',
    'Task.' => 'Задача',
    'Tasks - creating' => 'Задания - добавление',
    'Tasks - edit' => 'Задания - редактирование',
    'Tasks - manage' => 'Задания - управление',
    'Tasks - show' => 'Задания - просмотр',
    'Tasks creation and management module' => 'Модуль для создания заданий',
    'Tasks' => 'Задания',
    'team@yupe.ru' => 'team@yupe.ru',
    'This section represent queue management system' => 'В данном разделе представлены средства управления заданиями',
    'View task' => 'Просмотр задания',
    'Viewing queue' => 'Просмотр задания очереди',
    'Working' => 'В работе',
    'YQuemail.queueComponent contains bad identifier of queue component!' => 'YQuemail.queueComponent содержит неправильный идентификатор компонента queue!',
    'yupe team' => 'yupe team',
];
