<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Delete'                                                                                                                  => 'Удалить',
    'Do you really want to delete selected elements?'                                                                         => 'Вы уверены, что хотите удалить выбранные элементы?',
    '-unknown-'                                                                                                               => '-неизвестно-',
    '0.1'                                                                                                                     => '0.1',
    'CDbQueue.connectionId "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbQueue.connectionId "{id}" не верно. Пожалуйста буедитесь что вы ссылаетесь на верный ID компонента CDbConnection.',
    'Error json_encode !'                                                                                                     => 'Ошибка json_encode !',
    'ID'                                                                                                                      => 'ID',
    'YQuemail.queueComponent contains bad identifier of queue component!'                                                     => 'YQuemail.queueComponent содержит неправильный идентификатор компонента queue!',
    'http://yupe.ru'                                                                                                          => 'http://yupe.ru',
    'team@yupe.ru'                                                                                                            => 'team@yupe.ru',
    'yupe team'                                                                                                               => 'yupe team',
    'This section represent queue management system'                                                                          => 'В данном разделе представлены средства управления заданиями',
    'Working'                                                                                                                 => 'В работе',
    'Do you really want to delete?'                                                                                           => 'Вы уверены, что хотите удалить?',
    'Completed'                                                                                                               => 'Выполнена',
    'High'                                                                                                                    => 'Высокий',
    'Create task'                                                                                                             => 'Добавить задание',
    'Create task and close'                                                                                                   => 'Добавить задание и закрыть',
    'Create task and continue'                                                                                                => 'Добавить задание и продолжить',
    'Creation'                                                                                                                => 'Добавление',
    'Task creation'                                                                                                           => 'Добавление задания',
    'Completing'                                                                                                              => 'Завершение',
    'Task'                                                                                                                    => 'Задание',
    'Tasks'                                                                                                                   => 'Задания',
    'Tasks - creating'                                                                                                        => 'Задания - добавление',
    'Tasks - show'                                                                                                            => 'Задания - просмотр',
    'Tasks - edit'                                                                                                            => 'Задания - редактирование',
    'Tasks - manage'                                                                                                          => 'Задания - управление',
    'Task.'                                                                                                                   => 'Задача',
    'Record was created!'                                                                                                     => 'Запись добавлена!',
    'Record was updated!'                                                                                                     => 'Запись обновлена!',
    'Requested page was not found.'                                                                                           => 'Запрошенная страница не найдена.',
    'Find task'                                                                                                               => 'Искать задание',
    'Tasks creation and management module'                                                                                    => 'Модуль для создания заданий',
    'Start'                                                                                                                   => 'Начало',
    'Bad request. Please don\'t repeat similar requests anymore'                                                              => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
    'Low'                                                                                                                     => 'Низкий',
    'New'                                                                                                                     => 'Новая',
    'Normal'                                                                                                                  => 'Нормальный',
    'Handler'                                                                                                                 => 'Обработчик',
    'Queue cleaned!'                                                                                                          => 'Очередь очищена!',
    'Clean queue'                                                                                                             => 'Очистить очередь',
    'Error'                                                                                                                   => 'Ошибка',
    'Find tasks'                                                                                                              => 'Поиск заданий',
    'Fields with'                                                                                                             => 'Поля, отмеченные',
    'Notice'                                                                                                                  => 'Примечание',
    'Priority'                                                                                                                => 'Приоритет',
    'Show task'                                                                                                               => 'Просмотр задание',
    'View task'                                                                                                               => 'Просмотр задания',
    'Edit'                                                                                                                    => 'Редактирование',
    'Edit task'                                                                                                               => 'Редактирование задания',
    'Edit task.'                                                                                                              => 'Редактировать задание',
    'Services'                                                                                                                => 'Сервисы',
    'Created at'                                                                                                              => 'Создано',
    'Save blog and close'                                                                                                     => 'Сохранить блог и закрыть',
    'Save task'                                                                                                               => 'Сохранить задание',
    'Task list'                                                                                                               => 'Список заданий',
    'Status'                                                                                                                  => 'Статус',
    'Remove task'                                                                                                             => 'Удалить задание',
    'Management'                                                                                                              => 'Управление',
    'creation'                                                                                                                => 'добавление',
    'are required'                                                                                                            => 'обязательны.',
    'management'                                                                                                              => 'управление',
    'Manage queue'                                                                                                            => 'Управление очередями заданий',
    'Creating queue'                                                                                                          => 'Создание задания в очереди',
    'Removing queue'                                                                                                          => 'Удаление задания из очереди',
    'List of queue'                                                                                                           => 'Просмотр списка заданий очереди',
    'Editing queue'                                                                                                           => 'Редактирование задания очереди',
    'Viewing queue'                                                                                                           => 'Просмотр задания очереди',
);
