<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '0.2'                                                                => '',
    'IDE/Editors'                                                        => '',
    'YupeTeam'                                                           => '',
    'ZendSearch'                                                         => '',
    'http://yupe.ru'                                                     => '',
    'team@yupe.ru'                                                       => '',
    'Blogs'                                                              => '',
    'Enable'                                                             => '',
    'Abilities'                                                          => '',
    'Disable'                                                            => '',
    'RSS feed generation'                                                => '',
    'Module for project documentation'                                   => '',
    'Documentation'                                                      => '',
    'Using userspace settings'                                           => '',
    'Pages caching on filtration level'                                  => '',
    'Team'                                                               => '',
    'ConfigManager component'                                            => '',
    'Components'                                                         => '',
    'Memcached configuration'                                            => '',
    'Local docs'                                                         => '',
    'Migrator'                                                           => '',
    'Modules'                                                            => '',
    'Module for view and edit docs files (HTML and Markdown)'            => '',
    'Go home'                                                            => '',
    'Writing docs'                                                       => '',
    'Files settings'                                                     => '',
    'Undefined title'                                                    => '',
    'About Yupe!'                                                        => '',
    'About module'                                                       => '',
    'Curl wrapper'                                                       => '',
    'Updated {mtime}'                                                    => '',
    'Online docs'                                                        => '',
    'Methods description'                                                => '',
    'Optimal APC settings'                                               => '',
    'General module settings'                                            => '',
    'Show error'                                                         => '',
    'Show page for language by default'                                  => '',
    'Show error page if doc file in current language was not found?'     => '',
    'Help project'                                                       => '',
    'Problems of CWebUser and Gii module'                                => '',
    'Show local files'                                                   => '',
    'Working in eclipse'                                                 => '',
    'Development and support'                                            => '',
    'For developers'                                                     => '',
    'Docs files destination'                                             => '',
    'Modules docs files destination ({module} replaced by module title)' => '',
    'Extensions for HTML files'                                          => '',
    'Extensions for MarkDown files'                                      => '',
    'Docs page was not found'                                            => '',
    'Docs page was not found or it\'s empty'                             => '',
    'Existing files'                                                     => '',
    'Files'                                                              => '',
    'Files need display in control panel'                                => '',
    'Yupe!'                                                              => '内容',
    'Yupe! Documentation'                                                => '木星！文档',
    'Comment'                                                            => '',
    'Set testing environment'                                            => ''
];
