<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '*unknown*'                                                                     => '',
    '--choose--'                                                                    => '',
    '--no--'                                                                        => '',
    '0.5'                                                                           => '',
    'Id'                                                                            => '',
    'http://yupe.ru'                                                                => '',
    'team@yupe.ru'                                                                  => '',
    'yupe team'                                                                     => '',
    'Alias'                                                                         => '',
    'This section describes category management'                                    => '',
    'You are adding translate in to {lang}!'                                        => '',
    'Do you really want to remove category?'                                        => '',
    'Directory "{dir}" is available for write! {link}'                              => '',
    'Create category'                                                               => '',
    'Create category and close'                                                     => '',
    'Create category and continue'                                                  => '',
    'Add translate in to {lang}'                                                    => '',
    'Create'                                                                        => '',
    'Record was created!'                                                           => '',
    'Bad characters in {attribute} field'                                           => '',
    'Page was not found!'                                                           => '',
    'Change settings'                                                               => '',
    'Image'                                                                         => '',
    'Find category'                                                                 => '',
    'File uploading catalog (relatively Yii::app()->getModule("yupe")->uploadPath)' => '',
    'Categories'                                                                    => '',
    'Categories - show'                                                             => '',
    'Categories - edit'                                                             => '',
    'Categories - manage'                                                           => '',
    'Categories/Sections'                                                           => '',
    'Category'                                                                      => '',
    'Categories - create'                                                           => '',
    'Category was changed!'                                                         => '',
    'Short description'                                                             => '',
    'Module for categories/sections management'                                     => '',
    'On moderation'                                                                 => '',
    'Title'                                                                         => '',
    'Bad request. Please don\'t use similar requests anymore'                       => '',
    'Description'                                                                   => '',
    'Published'                                                                     => '',
    'Find category'                                                                 => '',
    'Fields with'                                                                   => '',
    'Menu items order'                                                              => '',
    'Show category'                                                                 => '',
    'View category'                                                                 => '',
    'Change'                                                                        => '',
    'Change category'                                                               => '',
    'Change translation in to {lang}'                                               => '',
    'Parent'                                                                        => '',
    'Save category and close'                                                       => '',
    'Save category and continue'                                                    => '',
    'Categories list'                                                               => '',
    'Status'                                                                        => '',
    'Structure'                                                                     => '',
    'Remove category'                                                               => '',
    'Manage'                                                                        => '',
    'Category manage'                                                               => '',
    'Targeting category was not found!'                                             => '',
    'Draft'                                                                         => '',
    'Language'                                                                      => '',
    'Language was not found!'                                                       => '',
    'create'                                                                        => '',
    'are required'                                                                  => '',
    'manage'                                                                        => '',
    'Select {field}'                                                                => '',
];
