<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '-неизвестно-' => '',
  '0.1' => '',
  'CDbQueue.connectionId "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => '',
  'Error json_encode !' => '',
  'ID' => '',
  'YQuemail.queueComponent содержит неправильный идентификатор компонента queue!' => '',
  'http://yupe.ru' => '',
  'team@yupe.ru' => '',
  'yupe team' => '',
  'В данном разделе представлены средства управления заданиями' => '',
  'В работе' => '',
  'Вы уверены, что хотите удалить?' => '',
  'Выполнена' => '',
  'Высокий' => '',
  'Добавить задание' => '',
  'Добавить задание и закрыть' => '',
  'Добавить задание и продолжить' => '',
  'Добавление' => '',
  'Добавление задания' => '',
  'Завершение' => '',
  'Задания' => 'Queue',
  'Задания - добавление' => '',
  'Задания - просмотр' => '',
  'Задания - редактирование' => '',
  'Задания - управление' => '',
  'Задача' => '',
  'Запись добавлена!' => '',
  'Запись обновлена!' => '',
  'Запрошенная страница не найдена.' => '',
  'Искать задание' => '',
  'Модуль для создания заданий' => '',
  'Начало' => '',
  'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы' => '',
  'Низкий' => '',
  'Новая' => '',
  'Нормальный' => '',
  'Обработчик' => '',
  'Очередь очищена!' => '',
  'Очистить очередь' => '',
  'Ошибка' => '',
  'Поиск заданий' => '',
  'Поля, отмеченные' => '',
  'Примечание' => '',
  'Приоритет' => '',
  'Просмотр задание' => '',
  'Просмотр задания' => '',
  'Редактирование' => '',
  'Редактирование задания' => '',
  'Редактировать задание' => '',
  'Сервисы' => '',
  'Создано' => '',
  'Сохранить блог и закрыть' => '',
  'Сохранить задание' => '',
  'Список заданий' => '',
  'Статус' => '',
  'Удалить задание' => '',
  'Управление' => '',
  'добавление' => '',
  'обязательны.' => '',
  'управление' => '',
);
