<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '-unknown-'                                                                                                               => '',
    '0.1'                                                                                                                     => '',
    'CDbQueue.connectionId "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => '',
    'Error json_encode !'                                                                                                     => '',
    'ID'                                                                                                                      => '',
    'YQuemail.queueComponent contains bad identifier of queue component!'                                                     => '',
    'http://yupe.ru'                                                                                                          => '',
    'team@yupe.ru'                                                                                                            => '',
    'yupe team'                                                                                                               => '',
    'This section represent queue management system'                                                                          => '',
    'Working'                                                                                                                 => '',
    'Do you really want to delete?'                                                                                           => '',
    'Completed'                                                                                                               => '',
    'High'                                                                                                                    => '',
    'Create task'                                                                                                             => '',
    'Create task and close'                                                                                                   => '',
    'Create task and continue'                                                                                                => '',
    'Creation'                                                                                                                => '',
    'Task creation'                                                                                                           => '',
    'Completing'                                                                                                              => '',
    'Task'                                                                                                                    => '',
    'Tasks'                                                                                                                   => '',
    'Tasks - creating'                                                                                                        => '',
    'Tasks - show'                                                                                                            => '',
    'Tasks - edit'                                                                                                            => '',
    'Tasks - manage'                                                                                                          => '',
    'Task.'                                                                                                                   => '',
    'Record was created!'                                                                                                     => '',
    'Record was updated!'                                                                                                     => '',
    'Requested page was not found.'                                                                                           => '',
    'Find task'                                                                                                               => '',
    'Tasks creation and management module'                                                                                    => '',
    'Start'                                                                                                                   => '',
    'Bad request. Please don\'t repeat similar requests anymore'                                                              => '',
    'Low'                                                                                                                     => '',
    'New'                                                                                                                     => '',
    'Normal'                                                                                                                  => '',
    'Handler'                                                                                                                 => '',
    'Queue cleaned!'                                                                                                          => '',
    'Clean queue'                                                                                                             => '',
    'Error'                                                                                                                   => '',
    'Find tasks'                                                                                                              => '',
    'Fields with'                                                                                                             => '',
    'Notice'                                                                                                                  => '',
    'Priority'                                                                                                                => '',
    'Show task'                                                                                                               => '',
    'View task'                                                                                                               => '',
    'Edit'                                                                                                                    => '',
    'Edit task'                                                                                                               => '',
    'Edit task.'                                                                                                              => '',
    'Services'                                                                                                                => '',
    'Created at'                                                                                                              => '',
    'Save blog and close'                                                                                                     => '',
    'Save task'                                                                                                               => '',
    'Task list'                                                                                                               => '',
    'Status'                                                                                                                  => '',
    'Remove task'                                                                                                             => '',
    'Management'                                                                                                              => '',
    'creation'                                                                                                                => '',
    'are required'                                                                                                            => '',
    'management'                                                                                                              => '',
];
