<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '*unknown*' => '*неизвестно*',
  '--choose--' => '--выберите--',
  '0.2' => '0.2',
  'Accepted extensions (separated by comma)' => 'Разрешенные расширения (перечислите через запятую)',
  'Active' => 'Доступен',
  'Add product' => 'Добавить товар',
  'Add product and close' => 'Добавить товар и закрыть',
  'Add product and continue' => 'Добавить товар и продолжить',
  'Added' => 'Добавлено',
  'Administration' => 'Управление',
  'Alias' => 'Алиас',
  'Are you sure you want to remove product?' => 'Вы уверены, что хотите удалить товар?',
  'Article' => 'Артикул',
  'Catalog for file uploads (relatively Yii::app()->getModule("yupe")->uploadPath)' => 'Каталог для загрузки файлов (относительно Yii::app()->getModule("yupe")->uploadPath)',
  'Category' => 'Категория',
  'Change settings' => 'Изменить настройки',
  'Content' => 'Контент',
  'Creating' => 'Добавление',
  'Data' => 'Данные',
  'Delete product' => 'Удалить товар',
  'Description' => 'Описание',
  'Directory "{dir}" is not accessible for write! {link}' => 'Директория "{dir}" не доступна для записи! {link}',
  'Edit product' => 'Редактировать товар',
  'Edited' => 'Изменено',
  'Edition' => 'Изменение',
  'Editor' => 'Изменил',
  'Fields with' => 'Поля помеченные',
  'Find product' => 'Найти товар',
  'Find products' => 'Поиск товаров',
  'ID' => 'ID',
  'Illegal characters in {attribute}' => 'Запрещенные символы в поле {attribute}',
  'Image' => 'Изображение',
  'Main category of products' => 'Главная категория каталога товаров',
  'Maximum size (in bytes)' => 'Максимальный размер (в байтах)',
  'Menu items order' => 'Порядок следования в меню',
  'Minimum size (in bytes)' => 'Минимальный размер (в байтах)',
  'Module for creating simple products catalog' => '',
  'No' => 'Нет',
  'Not active' => 'Не доступен',
  'Not available' => 'Нет в наличии',
  'Page was not found!' => 'Страница не найдена!',
  'Price' => 'Цена',
  'Product' => 'Товар',
  'Product view' => 'Просмотр товара',
  'Product was not found!' => 'ТОвар не найден!',
  'Products' => 'Товары',
  'Products - administration' => 'Товары - управление',
  'Products - creating' => 'Товары - добавление',
  'Products - edition' => 'Товары - редактирование',
  'Products - view' => 'Товары - просмотр',
  'Products admin' => 'Управление товарами',
  'Products administration' => 'Управление товарами',
  'Products catalog' => 'Каталог товаров',
  'Products list' => 'Список товаров',
  'Record was added!' => 'Запись добавлена!',
  'Record was removed!' => 'Запись удалена!',
  'Record was updated!' => 'Записб изменена!',
  'Remove product' => 'Удалить товар',
  'Save product and close' => 'Сохранить товар и закрыть',
  'Save product and continue' => 'Сохранить товар и продолжить',
  'Short description' => 'Короткое описание',
  'Special' => 'Спецпредложение',
  'Status' => 'Статус',
  'This section describes the controls of products' => 'В данном разделе представлены средства управления товарами',
  'Title' => 'Заголовок',
  'Unknown request. Don\'t use this request aymore!' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!',
  'Updated' => 'Обновлено',
  'User' => 'Добавил',
  'View product' => 'Просмотр товара',
  'Visual editor' => 'Визуальный редактор',
  'Yes' => 'Да',
  'administration' => 'управление',
  'creating' => 'создание',
  'http://yupe.ru' => 'http://yupe.ru',
  'is required.' => 'обязательны для запонения',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
);
