<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '*unknown*' => '*неизвестно*',
  '--choose--' => '--выберите--',
  '0.2' => '0.2',
  'Accepted extensions (separated by comma)' => 'Разрешенные расширения (перечислите через запятую)',
  'Active' => 'Доступен',
  'Add a product' => 'Добавить товар',
  'Add product and close' => 'Добавить товар и закрыть',
  'Add product and continue' => 'Добавить товар и продолжить',
  'Added' => 'Добавлено',
  'Manage' => 'Управление',
  'Alias' => 'Алиас',
  'Do you really want to remove product?' => 'Вы уверены, что хотите удалить товар?',
  'Article' => 'Артикул',
  'File uploads directory (relative to Yii::app()->getModule("yupe")->uploadPath)' => 'Каталог для загрузки файлов (относительно Yii::app()->getModule("yupe")->uploadPath)',
  'Category' => 'Категория',
  'Change settings' => 'Изменить настройки',
  'Content' => 'Контент',
  'Creating' => 'Добавление',
  'Data' => 'Данные',
  'Delete product' => 'Удалить товар',
  'Description' => 'Описание',
  'Directory "{dir}" is not writeable! {link}' => 'Директория "{dir}" не доступна для записи! {link}',
  'Update product' => 'Редактировать товар',
  'Edited' => 'Изменено',
  'Edition' => 'Изменение',
  'Editor' => 'Изменил',
  'Fields marked with' => 'Поля помеченные',
  'Find a product' => 'Найти товар',
  'Find products' => 'Поиск товаров',
  'ID' => 'ID',
  'Illegal characters in {attribute}' => 'Запрещенные символы в поле {attribute}',
  'Image' => 'Изображение',
  'Main category of products' => 'Главная категория каталога товаров',
  'Maximum size (in bytes)' => 'Максимальный размер (в байтах)',
  'Menu items order' => 'Порядок следования в меню',
  'Minimum size (in bytes)' => 'Минимальный размер (в байтах)',
  'This module allows creating a simple product catalog' => 'Модуль позволяет создавать простой каталог',
  'No' => 'Нет',
  'Not active' => 'Не доступен',
  'Not available' => 'Нет в наличии',
  'Page was not found!' => 'Страница не найдена!',
  'Price' => 'Цена',
  'Products' => 'Товары',
  'Product show' => 'Просмотр товара',
  'Product was not found!' => 'ТОвар не найден!',
  'Products' => 'Товары',
  'Manage products' => 'Товары - управление',
  'Products - creating' => 'Товары - добавление',
  'Products - edition' => 'Товары - редактирование',
  'Products - view' => 'Товары - просмотр',
  'Product admin' => 'Управление товарами',
  'Products administration' => 'Управление товарами',
  'Product catalog' => 'Каталог товаров',
  'Product list' => 'Список товаров',
  'Record was added!' => 'Запись добавлена!',
  'Record was removed!' => 'Запись удалена!',
  'Record was updated!' => 'Записб изменена!',
  'Remove product' => 'Удалить товар',
  'Save product and close' => 'Сохранить товар и закрыть',
  'Save product and continue' => 'Сохранить товар и продолжить',
  'Short description' => 'Короткое описание',
  'Special' => 'Спецпредложение',
  'Status' => 'Статус',
  'This section describes products manager' => 'В данном разделе представлены средства управления товарами',
  'Title' => 'Заголовок',
  'Unknown request. Don\'t repeat it please!' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!',
  'Updated' => 'Обновлено',
  'User' => 'Добавил',
  'Show product' => 'Просмотр товара',
  'Visual editor' => 'Визуальный редактор',
  'Yes' => 'Да',
  'administration' => 'управление',
  'creating' => 'создание',
  'http://yupe.ru' => 'http://yupe.ru',
  'are required.' => 'обязательны для запонения',
  'team@yupe.ru' => 'team@yupe.ru',
  'yupe team' => 'yupe team',
  'Constant link' => 'Постоянная ссылка',
);
