<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'Find (Zend) - manage' => 'Поиск (Zend) - управление',
    'Find (Zend)' => 'Поиск (Zend)',
    'Find module in terms of Zend Lucene' => 'Модуль поиска на основе Zend Lucene',
    'Find!' => 'Искать!',
    'For index creation, please click button below.' => 'Для создания или обновления индекса нажмите кнопку ниже.',
    'Index data folder.' => 'Папка хранения индекса поиска',
    'Index is updating... Wait please...' => 'Индекс обновляется... Подождите...',
    'Index updated successfully!' => 'Индекс успешно обновлен!',
    'Index' => 'Индексация',
    'Manage search index' => 'Управление поисковым индексом',
    'Manage' => 'Управление',
    'manage' => 'управление',
    'Models you want to index is necessary to describe in configuration file.' => 'Модели, которые вы хотите проиндексировать необходимо описать в конфигурационном файле.',
    'Module "{module}" not installed!' => 'Модуль "{module}" не установлен!',
    'Nothing was found' => 'Поиск не дал результатов.',
    'Page was not found!' => 'Страница не найдена!',
    'Reindex site' => 'Переиндексация сайта',
    'Results:' => 'Результаты',
    'Search by request: ' => 'Поиск по запросу: ',
    'Search' => 'Поиск',
    'Search...' => 'Поиск...',
    'Services' => 'Сервисы',
    'There is an error!' => 'Произошла ошибка!',
    'This module require "Iconv" extension!' => 'Данный модуль требует наличия "Iconv" расширения!',
    'Update config file or module, Module index not found for model "{model}"!' => 'Обновите конфигурационный файл модуля или настройки индексации, индекс "module" не найден в настройках для модели {model}',
    'Update find index' => 'Обновить поисковый индекс',
    'Wait please...' => 'Подождите...',
];
