<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    '0.2' => '0.2',
    'WebAction webstudio' => 'WebAction webstudio',
    'http://webaction.su' => 'http://webaction.su',
    'info@webaction.su' => 'info@webaction.su',
    'For index creation, please click button below.' => 'Для создания или обновления индекса нажмите кнопку ниже.',
    'Index is updating... Wait please...' => 'Индекс обновляется... Подождите...',
    'Index updated successfully!' => 'Индекс успешно обновлен!',
    'Models you want to index is necessary to describe in configuration file.' => 'Модели, которые вы хотите проиндексировать необходимо описать в конфигурационном файле.',
    'Find module in terms of Zend Lucene' => 'Модуль поиска на основе Zend Lucene',
    'Update find index' => 'Обновить поисковый индекс',
    'Index data folder.' => 'Папка хранения индекса поиска',
    'Wait please...' => 'Подождите...',
    'Find (Zend)' => 'Поиск (Zend)',
    'Find (Zend) - manage' => 'Поиск (Zend) - управление',
    'There is an error!' => 'Произошла ошибка!',
    'Services' => 'Сервисы',
    'Page was not found!' => 'Страница не найдена!',
    'Manage' => 'Управление',
    'manage' => 'управление',
    'Find!' => 'Искать!',
    'Search...' => 'Поиск...',
    'Search by request: ' => 'Поиск по запросу: ',
    'Results:' => 'Результаты',
    'Nothing was found' => 'Поиск не дал результатов.',
    'Update config file or module, Module index not found for model "{model}"!' => 'Обновите конфигурационный файл модуля или настройки индексации, индекс "module" не найден в настройках для модели {model}',
    'Module "{module}" not installed!' => 'Модуль "{module}" не установлен!',
    'This module require "Iconv" extension!' => 'Данный модуль требует наличия "Iconv" расширения!',
);
